joreilly/Confetti

- androidApp/src/main/java/dev/johnoreilly/kikiconf/android/KikiConfViewModel.kt
- androidApp/src/main/java/dev/johnoreilly/kikiconf/android/sessions/SessionView.kt
- shared/src/commonMain/graphql/Queries.graphql
(Colours still need some work :) )
> session list UI updates

- README.md
TIL git branch names support unicode 🙃
> Update project name according to new brand guidelines 😄

- .github/workflows/update-schema.yml
- README.md
- build.gradle.kts
- buildSrc/src/main/java/Dependencies.kt
- server/README.md
- server/build.gradle.kts
- server/src/main/appengine/app.yaml
- server/src/main/kotlin/fr/androidmakers/server/CachedData.kt
- server/src/main/kotlin/fr/androidmakers/server/DefaultApplication.kt
- server/src/main/kotlin/fr/androidmakers/server/graph.kt
- server/src/main/kotlin/fr/androidmakers/server/main.kt
- server/src/main/kotlin/fr/androidmakers/server/model/json-model.kt
- server/src/main/kotlin/fr/androidmakers/server/model/model.kt
- server/src/main/resources/application.yml
- server/src/main/resources/rooms.json
- server/src/main/resources/schedule.json
- server/src/main/resources/sessions.json
- server/src/main/resources/speakers.json
- settings.gradle.kts
- shared/build.gradle.kts
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/di/Koin.kt
Add a server module that hosts the code for https://confetti-349319.uw.r.appspot.com/playground
```
./gradlew :server:bootRun
./gradlew :server:appengineDeploy
```
> ☁️  Add a server module

- server/src/main/kotlin/fr/androidmakers/server/model/model.kt
See https://github.com/graphql/graphql-spec/issues/943
> 🧪 mark startInstant and endInstant as experimental

- .github/workflows/ios.yml
- .github/workflows/server-deploy.yml
- .github/workflows/server.yml
- .gitignore
- androidApp/src/main/java/dev/johnoreilly/confetti/rooms/RoomView.kt
Add iOS CI and add concurrency group for all workflows
> Add iOS CI

- backend/datastore/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/datastore/DataStore.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/DevFestNantes.kt
Closes https://github.com/joreilly/Confetti/issues/72
> fix endInstant and add breaks/lunch

- backend/datastore/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/datastore/DataStore.kt
- backend/datastore/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/datastore/model.kt
- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/graphql/DataStoreDataSource.kt
- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/graphql/model.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/DevFestNantes.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/DroidConSF.kt
Add
- Speaker.city
- Speaker.companyLogoUrl
- Session.complexity
- Session.feedbackId
See https://github.com/joreilly/Confetti/issues/73
I'm pretty sure `companyLogoUrl` returns a 404 at the moment, I'm not sure what the base url should be. To be continued...
> Add more fields

- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/graphql/DataStoreDataSource.kt
- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/graphql/model.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/DevFestNantes.kt
closes https://github.com/joreilly/Confetti/issues/73
> Add Session.type

- androidApp/build.gradle.kts
- androidApp/src/main/java/dev/johnoreilly/confetti/ConfettiViewModel.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/MainActivity.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/navigation/PeopleInSpaceNavHost.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/sessions/SessionView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/sessions/navigation/SessionsDestination.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/ui/ConfettiApp.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/ui/ConfettiAppState.kt
- buildSrc/src/main/java/Dependencies.kt
> initial adaptive layout implementation based on accompanist TwoPanel layout

- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/graphql/model.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/DevFestNantes.kt
See https://github.com/joreilly/Confetti/issues/79
> Deprecate link and populate url correctly

- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/DevFestNantes.kt
Closes https://github.com/joreilly/Confetti/issues/78
> Get the image extension from the file name

- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/DefaultApplication.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/FrenchKit.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/Main.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/di/Koin.kt
A bit late to the party but it's there 🎊 
[androidApp-debug.apk](https://storage.googleapis.com/martin-public/androidApp-debug.apk)
> Frenchkit 2022

- README.md
- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/DefaultApplication.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/FrenchKit.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/Main.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/Sessionize.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/utils.kt
Use `?conference=droidconlondon2022` to get it
> Add DroidConLondon data

- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/DefaultApplication.kt
- backend/service-import/build.gradle.kts
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/GraphQLSummit.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/Main.kt
- backend/service-import/src/jvmTest/kotlin/test/MainTest.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/di/Koin.kt
In the vein of "the conference app that's only available on day 2", I present GraphQL Summit 😅
> Add GraphQL Summit

- .github/workflows/ios.yml
- buildSrc/src/main/java/Dependencies.kt
- compoe 1.3.0.rc01
- update github actions ios workflow
> compose 1.3.0.rc01

- androidApp/src/main/java/dev/johnoreilly/confetti/di/AppModule.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/navigation/PeopleInSpaceNavHost.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/speakerdetails/SpeakerDetailsView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/speakerdetails/SpeakerDetailsViewModel.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/speakerdetails/navigation/SpeakerDetailsDestination.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/speakers/SpeakerView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/speakers/navigation/SpeakersDestination.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/di/Koin.kt
> Compose Speaker details screen

- androidApp/src/main/java/dev/johnoreilly/confetti/ConfettiViewModel.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/sessions/SessionView.kt
- shared/build.gradle.kts
- shared/src/commonMain/graphql/Queries.graphql
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/ConfettiRepository.kt
iOS pull to refresh is still TODO
> Get everything at startup and add pull to refresh

- androidApp/src/main/java/dev/johnoreilly/confetti/sessiondetails/SessionDetailsView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/sessions/SessionView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/speakerdetails/SpeakerDetailsView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/speakers/SpeakerView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/ui/ConfettiAppState.kt
- iosApp/iosApp/ConfettiViewModel.swift
- iosApp/iosApp/ContentView.swift
- iosApp/iosApp/Sessions/SessionDetailsView.swift
- iosApp/iosApp/Sessions/SessionListView.swift
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/di/Koin.kt
- set droidcon london as default conference
- swiftui/compose UI updates
> default to droidcon london + swiftui/compose UI updates

- androidApp/src/main/java/dev/johnoreilly/confetti/sessiondetails/SessionDetailsView.kt
- iosApp/iosApp.xcodeproj/project.pbxproj
- iosApp/iosApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- iosApp/iosApp/Sessions/SessionDetailsView.swift
> use flow layout for tags in SwfitUI client

- androidApp/src/main/java/dev/johnoreilly/confetti/ConfettiViewModel.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/rooms/RoomView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/sessions/SessionView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/speakers/SpeakerView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/ui/component/TopAppBar.kt
- iosApp/iosApp/ConfettiViewModel.swift
- iosApp/iosApp/Sessions/SessionListView.swift
- shared/src/commonMain/graphql/Queries.graphql
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/ConfettiRepository.kt
> show conference name in Android and iOS clients

- androidApp/src/main/java/dev/johnoreilly/confetti/ConfettiViewModel.kt
- iosApp/iosApp/ConfettiViewModel.swift
- shared/src/androidMain/kotlin/dev/johnoreilly/confetti/di/KoinAndroid.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/ConfettiRepository.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/di/Koin.kt
- shared/src/iosMain/kotlin/dev/johnoreilly/confetti/di/KoiniOS.kt
- shared/src/jvmMain/kotlin/dev/johnoreilly/confetti/di/KoinJVM.kt
Still hardcoded to a particular conference but provided by UI layer now.....next step is to create UI to allow user to select the conference.
> Allow setting conference dynamically

- androidApp/src/main/java/dev/johnoreilly/confetti/ConfettiViewModel.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/MainActivity.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/conferences/ConferencesView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/conferences/navigation/ConferencesDestination.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/navigation/ConfettiNavHost.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/sessions/SessionView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/sessions/navigation/SessionsDestination.kt
- iosApp/iosApp.xcodeproj/xcshareddata/xcschemes/iosApp.xcscheme
- shared/src/androidMain/kotlin/dev/johnoreilly/confetti/di/KoinAndroid.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/AppSettings.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/ConfettiRepository.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/di/Koin.kt
- shared/src/iosMain/kotlin/dev/johnoreilly/confetti/di/KoiniOS.kt
- shared/src/jvmMain/kotlin/Main.kt
- shared/src/jvmMain/kotlin/dev/johnoreilly/confetti/di/KoinJVM.kt
Minimal UI for now to show initial landing screen to allow selection of conference....which is then persisted and used next time app is launched.  
Have also added overflow menu to allow bring up conference selection UI again after one has been chosen.
> allow selection of conference in android client

- androidApp/src/main/java/dev/johnoreilly/confetti/ConfettiViewModel.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/sessions/SessionView.kt
> initial work to show grid view for tablets etc

- androidApp/src/main/java/dev/johnoreilly/confetti/navigation/ConfettiNavHost.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/speakers/SpeakerView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/speakers/navigation/SpeakersDestination.kt
> initial work to show speakers view for tablets etc

- androidApp/build.gradle.kts
- androidApp/src/main/AndroidManifest.xml
- androidApp/src/main/java/dev/johnoreilly/confetti/sessions/SessionListGridView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/sessions/SessionListView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/sessions/SessionView.kt
- build.gradle.kts
- buildSrc/src/main/java/Dependencies.kt
- shared/build.gradle.kts
- shared/src/androidMain/AndroidManifest.xml
- update AGP version to 7.3.1
- revert koin version for now to fix release build crash
- session list compose ui updates
> koin revert

- androidApp/build.gradle.kts
- androidApp/proguard-rules.pro
- androidApp/src/main/java/dev/johnoreilly/confetti/ConfettiApplication.kt
- backend/datastore/build.gradle.kts
- backend/service-graphql/build.gradle.kts
- backend/service-import/build.gradle.kts
- build.gradle.kts
- buildSrc/src/main/java/Dependencies.kt
- gradle.properties
- gradle/libs.versions.toml
- gradle/wrapper/gradle-wrapper.properties
- iosApp/iosApp.xcodeproj/project.pbxproj
- iosApp/iosApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- iosApp/iosApp.xcodeproj/xcuserdata/joreilly.xcuserdatad/xcschemes/xcschememanagement.plist
- iosApp/iosApp/ConfettiViewModel.swift
- settings.gradle.kts
- shared/build.gradle.kts
- shared/src/androidMain/kotlin/dev/johnoreilly/confetti/utils/AndroidDateTimeFormatter.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/ConfettiRepository.kt
- kotlin 1.8.0-RC related changes
- switch to version catalogs
- make R8 happy
- typo
- remove lint warning
- build updates
> kotlin 1 8

- wearApp/build.gradle.kts
- wearApp/src/main/AndroidManifest.xml
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/MainActivity.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/conferences/ConferencesView.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/conferences/navigation/ConferencesDestination.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/ui/ConfettiApp.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/ui/Theme.kt
> Beautify the Conferences Screen

- wearApp/src/main/java/dev/johnoreilly/confetti/wear/sessions/SessionListView.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/sessions/SessionView.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/sessions/navigation/SessionsDestination.kt
> Sessions Screen cleanup

- wearApp/src/main/java/dev/johnoreilly/confetti/wear/sessiondetails/SessionDetailsView.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/sessiondetails/SessionSpeakerInfo.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/sessiondetails/navigation/SessionDetailsDestination.kt
- wearApp/src/main/res/drawable/ic_person_black_24dp.xml
> Update Details Page

- .github/workflows/update-schema.yml
Apply [the advice I'm giving to everyone else](https://github.com/martinbonnin/pin-github-actions) to myself 😁
> Pin the update-graphql-schema action

- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/Fosdem.kt
> Strip HTML on the backend

- wearApp/src/main/java/dev/johnoreilly/confetti/wear/ui/ConfettiApp.kt
address https://github.com/joreilly/Confetti/issues/203
> fix issue in wear app switching conferences

- wearApp/src/main/java/dev/johnoreilly/confetti/wear/conferences/ConferencesView.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/home/homeListView.kt
fixes https://github.com/joreilly/Confetti/issues/202
> fix issue in wear app with showing of progress indicator

- .gitignore
- backend/datastore/build.gradle.kts
- backend/datastore/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/datastore/DataStore.kt
- backend/datastore/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/datastore/model.kt
- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/graphql/DataStoreDataSource.kt
- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/graphql/model.kt
- backend/service-import/build.gradle.kts
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/DeepAI.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/DevFestNantes.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/DroidConSF.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/Fosdem.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/FrenchKit.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/GraphQLSummit.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/Main.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/Sessionize.kt
shortDescription is only available for `droidconlondon2022` at the time being. It's using [DeepAI](https://deepai.org/machine-learning-model/summarization) to create the summary, which TBH doesn't work super well but was fun to do. Ultimately, we should provide a manual way to set this.
> Add Session.shortDescription for watches

- androidApp/build.gradle.kts
- androidApp/src/main/java/dev/johnoreilly/confetti/ConfettiApplication.kt
- wearApp/build.gradle.kts
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/ConfettiApplication.kt
Use it to filter down the crashes
> Log appName to crashlytics

- androidApp/build.gradle.kts
- wearApp/build.gradle.kts
> Avoid gradle warnings

- androidApp/src/main/java/dev/johnoreilly/confetti/sessions/SessionView.kt
- fastlane/Fastfile
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/home/homeListView.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/home/homeView.kt
Can maybe find better place for this but just to have option for now in case data is stale.
> add refresh option to wear app

- androidApp/src/main/java/dev/johnoreilly/confetti/MainActivity.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/ui/ConfettiApp.kt
- shared/build.gradle.kts
- shared/src/androidMain/kotlin/dev/johnoreilly/confetti/analytics/AndroidLoggingAnalyticsLogger.kt
- shared/src/androidMain/kotlin/dev/johnoreilly/confetti/analytics/FirebaseAnalyticsLogger.kt
- shared/src/androidMain/kotlin/dev/johnoreilly/confetti/analytics/NavigationHelper.kt
- shared/src/androidMain/kotlin/dev/johnoreilly/confetti/di/KoinAndroid.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/analytics/AnalyticsEvent.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/analytics/AnalyticsLogger.kt
- wearApp/build.gradle.kts
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/MainActivity.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/sessiondetails/SessionDetailsViewModel.kt
Just starting with navigation events.
> Add Firebase analytics

- wearApp/src/main/java/dev/johnoreilly/confetti/wear/tile/CurrentSessionsTileService.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/tile/TileAnalyticsEvent.kt
```
2023-02-12 06:54:24.651  2246-2246  Analytics               dev.johnoreilly.confetti             I  tile_add {}
2023-02-12 06:55:42.935  2246-2246  Analytics               dev.johnoreilly.confetti             I  tile_enter {conference=frenchkit2022}
2023-02-12 06:55:45.114  2246-2246  Analytics               dev.johnoreilly.confetti             I  tile_leave {conference=frenchkit2022}
```
> Add tile analytics

- README.md
Works better in dark more
Before
After
> Use App Store logo with transparent background

- androidApp/src/main/java/dev/johnoreilly/confetti/ConfettiApplication.kt
Don't assume Firebase is setup in debug builds
> Avoid debug firebase dependency

- androidApp/src/main/java/dev/johnoreilly/confetti/MainActivity.kt
- gradle/libs.versions.toml
- shared/build.gradle.kts
- shared/src/androidMain/kotlin/dev/johnoreilly/confetti/di/KoinAndroid.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/AppSettings.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/ConfettiRepository.kt
- shared/src/iosMain/kotlin/dev/johnoreilly/confetti/di/KoiniOS.kt
- shared/src/jvmMain/kotlin/dev/johnoreilly/confetti/di/KoinJVM.kt
- shared/src/mobileMain/kotlin/dev/johnoreilly/confetti/ConfettiViewModel.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/MainActivity.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/tile/CurrentSessionsTileService.kt
Use FlowSettings.
This also exposes some hidden blocking calls, in this PR these are TODOs. A bigger PR https://github.com/joreilly/Confetti/pull/245 I'm splitting avoid this.
> Use FlowSettings

- settings.gradle.kts
> Error if the build is run with Java < 17

- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/ConfettiRepository.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/MainActivity.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/conferences/ConferencesView.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/conferences/ConferencesViewModel.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/di/AppModule.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/home/HomeViewModel.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/home/homeView.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/home/navigation/homeDestination.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/tile/CurrentSessionsData.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/tile/CurrentSessionsTileRenderer.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/tile/CurrentSessionsTileService.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/ui/ConfettiApp.kt
Completing refactoring the app navigation.
Note: there are still TODOs where we were already having blocking calls in the main path.
Next, probably profile and optimise queries to make sure we don't over fetch.
> Make Home a non special destination

- shared/build.gradle.kts
- shared/src/commonMain/graphql/extra.graphqls
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/complication/NextSessionTemplate.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/home/homeListView.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/sessiondetails/SessionDetailsView.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/sessions/sessionsListView.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/tile/CurrentSessionsTileRenderer.kt
See https://github.com/joreilly/Confetti/pull/263
> Configure cache ids

- shared/src/mobileMain/kotlin/dev/johnoreilly/confetti/ConfettiViewModel.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/MainActivity.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/home/HomeViewModel.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/home/homeListView.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/home/homeView.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/home/navigation/conferenceHomeDestination.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/tile/CurrentSessionsTileRenderer.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/ui/ConfettiApp.kt
Use Conference Home as the start destination.  Navigate to conference list if no default.
Also removes a runBlocking from the main activity.
> Change Wear navigation

- .github/workflows/android_wear_jvm.yml
- gradle.properties
- shared/build.gradle.kts
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/ApolloClientCache.kt
- shared/src/jvmMain/kotlin/Main.kt
Closes https://github.com/joreilly/Confetti/issues/258
> Run JVM in CI

- backend/datastore/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/datastore/DataStore.kt
- backend/datastore/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/datastore/model.kt
- backend/service-graphql/index.yaml
- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/DefaultApplication.kt
- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/graphql/DataSource.kt
- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/graphql/DataStoreDataSource.kt
- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/graphql/model.kt
> Add sessions(filter, order)

- wearApp/src/main/java/dev/johnoreilly/confetti/wear/ui/Theme.kt
See https://medium.com/androiddevelopers/fixing-font-padding-in-compose-text-768cd232425b
May as well build for the future for a new app.
> Adopt Compose future Text padding now

- wearApp/src/androidTest/java/dev/johnoreilly/confetti/wear/ScreenshotTest.kt
Was not compiling, and wasn't enforcing screen was showing.
> Fix android test and make stricter

- androidApp/build.gradle.kts
- androidApp/src/main/java/dev/johnoreilly/confetti/ConfettiApplication.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/di/AppModule.kt
- shared/build.gradle.kts
- shared/src/androidMain/kotlin/dev/johnoreilly/confetti/work/WorkManagerConferenceRefresh.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/ConfettiRepository.kt
- shared/src/iosMain/kotlin/dev/johnoreilly/confetti/di/KoiniOS.kt
- shared/src/jvmMain/kotlin/Main.kt
- shared/src/mobileMain/kotlin/dev/johnoreilly/confetti/ConferenceRefresh.kt
- shared/src/mobileMain/kotlin/dev/johnoreilly/confetti/ConfettiViewModel.kt
- shared/src/mobileMain/kotlin/dev/johnoreilly/confetti/JobConferenceRefresh.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/conferences/ConferencesViewModel.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/di/AppModule.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/home/HomeViewModel.kt
Use WorkManager on mobile also.
Removes the refresh from setConference.
> Use a separate refresh job

- androidApp/src/main/java/dev/johnoreilly/confetti/sessions/SessionListGridView.kt
- fastlane/Fastfile
> wide screen updates

- backend/datastore/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/datastore/ConferenceId.kt
- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/CacheControlInstrumentation.kt
- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/DefaultApplication.kt
- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/graphql/TestDataSource.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/Main.kt
Use `"test"` as a HTTP header to get test data:
```json
{
"data": {
"sessions": {
"nodes": [
{
"id": "session0",
"title": "#0 - 2023-03-16T17:02:05.618060"
},
{
"id": "session1",
"title": "#1 - 2023-03-16T17:02:05.618060"
},
{
"id": "session2",
"title": "#2 - 2023-03-16T17:02:05.618060"
}
```
> Add a test conference

- gradle/libs.versions.toml
- wearApp/build.gradle.kts
- wearApp/src/androidTest/java/dev/johnoreilly/confetti/wear/AppTest.kt
- wearApp/src/androidTest/java/dev/johnoreilly/confetti/wear/InstrumentationTestRunner.kt
- wearApp/src/androidTest/java/dev/johnoreilly/confetti/wear/TestApplication.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/MainActivity.kt
- wearApp/src/test/kotlin/dev/johnoreilly/confetti/wear/AppTest.kt
- wearApp/src/test/kotlin/dev/johnoreilly/confetti/wear/KoinTestApp.kt
Following https://insert-koin.io/docs/reference/koin-android/instrumented-testing some what
Just putting tests in place.
> Add base tests for Wear

- .github/workflows/android_wear_jvm.yml
- .github/workflows/backend-deploy.yml
- .github/workflows/backend-test.yml
- .github/workflows/build-apps.yml
- .github/workflows/ios.yml
Nice speed up through caching the jobs (when run on main).
> Use gradle-build-action

- .github/workflows/android_wear_jvm.yml
- .github/workflows/wear_instrumentation.yml
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/MainActivity.kt
Add a Wear instrumentation test, guarded by a label so it doesn't burn github CI minutes.
> Wear instrumentation test

- shared/src/mobileMain/kotlin/dev/johnoreilly/confetti/navigation/SpeakerDetailsKey.kt
- wearApp/src/androidTest/java/dev/johnoreilly/confetti/wear/ScreenshotTest.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/di/AppModule.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/sessiondetails/SessionDetailsView.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/sessiondetails/SessionSpeakerInfo.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/sessiondetails/navigation/SessionDetailsDestination.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/sessions/navigation/sessionsDestination.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/sessions/sessionsListView.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/speakerdetails/SpeakerDetailsView.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/speakerdetails/SpeakerDetailsViewModel.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/speakerdetails/navigation/SpeakerDetailsDestination.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/ui/ConfettiApp.kt
Addresses https://github.com/joreilly/Confetti/issues/336
> Show speaker details in wear app

- fastlane/Fastfile
I really need to setup something to automate this at some point!
> update play store versions

- androidApp/src/main/java/dev/johnoreilly/confetti/conferences/ConferencesView.kt
- iosApp/ConfettiTests/ConfettiTests.swift
- iosApp/iosApp.xcodeproj/project.pbxproj
- iosApp/iosApp.xcodeproj/xcshareddata/xcschemes/iosApp.xcscheme
- iosApp/iosApp/ConfettiApp.swift
- shared/src/mobileMain/kotlin/dev/johnoreilly/confetti/ConferencesViewModel.kt
currently just this one
```
func testGetConferences() async throws {
let viewModel = ConferencesViewModel()
let confUIStateSequence = asyncSequence(for: viewModel.uiStateFlow)
let uiState = try await confUIStateSequence.first(where: { $0 is ConferencesViewModel.Success })
let conferences = (uiState as! ConferencesViewModel.Success).conferences
XCTAssert(!conferences.isEmpty)
}
```
> add initial swift unit test

- backend/datastore/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/datastore/DataStore.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/DevFestNantes.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/DroidConSF.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/Fosdem.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/FrenchKit.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/GraphQLSummit.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/Main.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/Sessionize.kt
- backend/service-import/src/main/appengine/app.yaml
Fixes 
```
curl -X POST https://import-dot-confetti-349319.uw.r.appspot.com/update/kotlinconf2023
```
> use java17 in GCP, return number of updated sessions

- iosApp/iosApp/ConfettiApp.swift
- iosApp/iosApp/Sessions/SessionDetailsView.swift
- iosApp/iosApp/Sessions/SessionListView.swift
> feat(ui): fix dark theme for iOS app

- androidApp/src/main/java/dev/johnoreilly/confetti/sessions/SessionListView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/sessions/SessionsView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/speakers/SpeakerView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/ui/ConfettiScaffold.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/ConfettiRepository.kt
- shared/src/mobileMain/kotlin/dev/johnoreilly/confetti/SessionsViewModel.kt
> add a snackBar when a bookmark error happens

- androidApp/src/main/java/dev/johnoreilly/confetti/wear/WearSettingsSync.kt
Use a lazy to avoid reading from DataLayer APIs before checking availability
> Fix DataLayer usage before install

- androidApp/src/main/java/dev/johnoreilly/confetti/sessions/SessionListView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/sessions/SessionsView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/ui/SigninDialog.kt
Display a sign in prompt if the user is not logged in and tries to add a bookmark
Closes https://github.com/joreilly/Confetti/issues/302#issuecomment-1478551904
> Sign in prompt

- androidApp/src/main/java/dev/johnoreilly/confetti/MainActivity.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/account/AccountIcon.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/di/AppModule.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/settings/SettingsDialog.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/settings/SettingsViewModel.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/ui/ConfettiAppState.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/ui/ConfettiScaffold.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/ui/Theme.kt
- androidApp/src/main/res/values/strings.xml
- fastlane/Fastfile
- fastlane/README.md
> Theme settings screen

- README.md
- build.gradle.kts
- compose-desktop/build.gradle.kts
- compose-desktop/src/main/kotlin/main.kt
- settings.gradle.kts
This is missing of course tons of stuff but it's at least a start.  It's also not sharing any of the Compose code with other clients but also opportunity to do that.
> Initial basic version of Compose for Desktop client

- androidApp/src/main/java/dev/johnoreilly/confetti/sessions/SessionsView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/ui/ConfettiScaffold.kt
- shared/src/mobileMain/kotlin/dev/johnoreilly/confetti/SessionsViewModel.kt
A naive implementation of search sessions. The search component is simple but does look nice - and includes a transition animation. The same approach can be extended to speakers.
Fixes #305
[search-1.webm](https://user-images.githubusercontent.com/4348197/227663902-74ba721a-ab13-404a-a175-21d371330137.webm)
> Adds search sessions feature to Android

- backend/datastore/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/datastore/DataStore.kt
- backend/datastore/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/datastore/model.kt
- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/graphql/DataSource.kt
- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/graphql/DataStoreDataSource.kt
- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/graphql/TestDataSource.kt
- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/graphql/model.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/Main.kt
- backend/service-import/src/jvmTest/kotlin/test/MainTest.kt
Closes https://github.com/joreilly/Confetti/issues/407
> Add Speaker.conference and Query.speaker(id)

- .github/workflows/android_wear_jvm.yml
Remove wear androidTest
Split out android and JVM so they run concurrently
> Split up builds

- wearApp/src/test/kotlin/dev/johnoreilly/confetti/wear/ConferenceScreenTest.kt
- wearApp/src/test/kotlin/dev/johnoreilly/confetti/wear/Diffing.kt
- wearApp/src/test/kotlin/dev/johnoreilly/confetti/wear/ScreenshotTest.kt
- wearApp/src/test/kotlin/dev/johnoreilly/confetti/wear/SessionsDetailsTest.kt
- wearApp/src/test/kotlin/dev/johnoreilly/confetti/wear/SessionsScreenTest.kt
Example diffs, without tolerances
> Have screenshot tolerances for platform differences

- wearApp/src/main/java/dev/johnoreilly/confetti/wear/auth/navigation/authDestination.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/conferences/navigation/ConferencesDestination.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/home/navigation/conferenceHomeDestination.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/sessions/navigation/sessionsDestination.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/settings/navigation/SettingsDestination.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/speakerdetails/navigation/SpeakerDetailsDestination.kt
- wearApp/src/test/kotlin/dev/johnoreilly/confetti/wear/AppTest.kt
- wearApp/src/test/kotlin/dev/johnoreilly/confetti/wear/BaseAppTest.kt
- wearApp/src/test/kotlin/dev/johnoreilly/confetti/wear/NavigationTest.kt
#fixes https://github.com/joreilly/Confetti/issues/173
> Add Wear Deeplinks

- androidApp/src/main/java/dev/johnoreilly/confetti/ConfettiApplication.kt
- compose-desktop/src/main/kotlin/main.kt
- gradle/libs.versions.toml
- shared/build.gradle.kts
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/ConfettiApplication.kt
While contributing to the multiplatform client code, I missed a logging solution. I'm not sure if `Napier` is the best solution out there but it is the only one I found supporting all platforms we support.
https://github.com/AAkira/Napier
What do you folks think of it?
> Add Multiplatform Logging

- androidApp/src/main/java/dev/johnoreilly/confetti/speakerdetails/SpeakerDetailsView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/speakerdetails/navigation/SpeakerDetailsDestination.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/ui/ConfettiApp.kt
- fastlane/Fastfile
- shared/src/commonMain/graphql/Queries.graphql
- wearApp/src/test/kotlin/dev/johnoreilly/confetti/wear/screenshots/TestFixtures.kt
Can navigate to session from here as well.  Probably needs some styling improvements....
> show speaker sessions in speaker details screen (compose for now)

- androidApp/src/main/java/dev/johnoreilly/confetti/MainActivity.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/settings/SettingsDialog.kt
- fastlane/Fastfile
> fix dynamic color setting logic + add update wear theme option to setting screen

- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/DefaultApplication.kt
fixes #275
```
{
"timestamp": "2023-03-27T11:27:00.126+00:00",
"path": "/graphql",
"status": 500,
"error": "Internal Server Error",
"message": "Unknown conference: '', use Query.conferences without a header to get the list of possible values.",
"requestId": "45a743d1-1"
}
```
> Backend: show better error message in the case of BadConferenceException

- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/ApolloClientCache.kt
- shared/src/mobileMain/kotlin/dev/johnoreilly/confetti/SessionsViewModel.kt
Simplify a bit the error logic
> GraphQL: ignore partial data

- gradle/libs.versions.toml
- shared/build.gradle.kts
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/ApolloClientCache.kt
I don't think we need to color those functions? Or do we?
> Make ApolloClientCache.clientFor non-suspend

- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/graphql/model.kt
- backend/service-import/build.gradle.kts
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/Sessionize.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/partners.kt
- add AndroidMakers 2023 partners and enable conference
> Add AndroidMakers 2023 speakers and un-hide it

- androidApp/src/main/java/dev/johnoreilly/confetti/bookmarks/BookmarksRoute.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/bookmarks/BookmarksView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/bookmarks/navigation/BookmarksKey.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/di/AppModule.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/navigation/TopLevelDestination.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/search/navigation/bookmarksKey.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/ui/ConfettiApp.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/ui/ConfettiBottomBar.kt
- androidApp/src/main/res/values/strings.xml
- shared/src/mobileMain/kotlin/dev/johnoreilly/confetti/BookmarksViewModel.kt
Includes a bookmark tab, which shows the user's bookmark in a list. No past/upcoming support yet.
Fixes #466
> Add bookmarks tab

- backend/datastore/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/datastore/DataStore.kt
- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/graphql/DataSource.kt
- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/graphql/DataStoreDataSource.kt
- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/graphql/TestDataSource.kt
- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/graphql/model.kt
- iosApp/ConfettiTests/ConfettiTests.swift
- shared/build.gradle.kts
- shared/src/commonMain/graphql/Queries.graphql
- shared/src/commonMain/graphql/schema.graphqls
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/ApolloClientCache.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/work/work.kt
- shared/src/mobileMain/kotlin/dev/johnoreilly/confetti/SessionsViewModel.kt
- shared/src/mobileMain/kotlin/dev/johnoreilly/confetti/SpeakerDetailsViewModel.kt
- shared/src/mobileMain/kotlin/dev/johnoreilly/confetti/SpeakersViewModel.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/speakerdetails/SpeakerDetailsViewModel.kt
Adds pagination to speakers on the backend. This is not really useful for the mobile app at the moment (where I've passed `first: 1000`) but could be useful in the future. Feel free to ignore it if it's more trouble than usefulness 😅
> Add pagination to the speakers field (backend only)

- androidApp/src/main/java/dev/johnoreilly/confetti/sessiondetails/SessionDetailsView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/sessiondetails/SessionSpeakerInfo.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/sessions/SessionListView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/speakerdetails/SpeakerDetailsView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/speakers/SpeakerView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/ui/component/SocialIcon.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/Model.kt
- Use sticky headers for the start time
Before / After
<table>
<tr><td>
</td><td>
</td></tr>
</table>
Before / After
<table>
<tr><td>
</td><td>
</td><td>
<tr><td>
</td><td>
</td></tr>
</table>
Before / After
<table>
<tr><td>
</td><td>
</td><td>
<tr><td>
</td><td>
</td></tr>
</table>
Before / After
<table>
<tr><td>
</td><td>
</td></tr>
</table>
> A few UI tweaks

- iosApp/iosApp/Speakers/SpeakerDetailsView.swift
fixes https://github.com/joreilly/Confetti/issues/430
> iOS: show session in speaker details screen

- iosApp/iosApp/Sessions/SessionListView.swift
- iosApp/iosApp/Sessions/SessionSpeakerInfo.swift
- iosApp/iosApp/Speakers/SpeakerListView.swift
fixes https://github.com/joreilly/Confetti/issues/354
https://user-images.githubusercontent.com/6302/229359888-54a258e8-e52c-40d1-8470-b680d5c190bc.mp4
> iOS SwiftUI updates

- androidApp/src/main/java/dev/johnoreilly/confetti/account/AccountIcon.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/account/AccountViewModel.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/settings/SettingsDialog.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/settings/SettingsViewModel.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/wear/WearSettingsSync.kt
- shared/src/commonMain/proto/wear.proto
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/preview/TestFixtures.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/settings/PhoneSettingsSync.kt
I got some bizarre error with ColourSpace when applying a theme.  Fix to use safer Int path.  
The full representation is here https://developer.android.com/reference/kotlin/androidx/compose/ui/graphics/Color#representation
> Change Wear Theme to use safer route for Int colours.

- androidApp/src/main/java/dev/johnoreilly/confetti/speakers/SpeakerView.kt
> show tagline info in speaker list

- .github/workflows/android_wear_jvm.yml
assembleDebug seems to take a long time, then fail on unit tests.  Reorder this.
> Test before assemble

- androidApp/src/main/java/dev/johnoreilly/confetti/speakerdetails/SpeakerDetailsView.kt
- fastlane/Fastfile
> fix speaker name alignment

- backend/service-graphql/build.gradle.kts
- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/DefaultApplication.kt
- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/UpdateSchema.kt
- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/main.kt
- shared/src/commonMain/graphql/schema.graphqls
Follow up from https://github.com/joreilly/Confetti/pull/481
It's better to send the full schema so that clients know what version of the spec a given server is supporting
Also: 
* sort the schema using a more sensible sorter
* add `./gradlew updateSchema` to update the local schema with the current state of the backend
> Send the full schema to Studio

- androidApp/src/main/java/dev/johnoreilly/confetti/sessions/SessionListGridView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/sessions/SessionsRoute.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/ui/ConfettiNavRail.kt
Also I added the bookmark top level destination to the navigation rail. I'm not 100% sure about the design on this, so I'm leaving it a draft PR :) I also would like to add some robolectric tests to test the compose logic if that is okay? :) 
This relates to #382 
Here is what it looks like now:
If u have not signed in and clicks the bookmark
> Add bookmarks to tablet session view

- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/ApolloClientCache.kt
From https://github.com/apollographql/apollo-kotlin/pull/4836/files
> Fix error handling from Apollo snapshots

- androidApp/src/main/java/dev/johnoreilly/confetti/speakers/SpeakerView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/ui/ConfettiScaffold.kt
- shared/src/mobileMain/kotlin/dev/johnoreilly/confetti/SessionsViewModel.kt
Also a couple of code scouting changes, if you don't want PRs to change unrelated things let me know and I can remove them, otherwise I might consider doing more of them in other PRs, whatever you prefer.
| --- | --- |
| https://user-images.githubusercontent.com/44558292/230501411-59057a8f-db77-4332-b701-8ba2adcbefb8.mp4 | https://user-images.githubusercontent.com/44558292/230501427-10aa2402-71db-40ac-a2df-35056e70bcac.mp4 |
> Fix Speaker expanded screen not having clickable items

- androidApp/src/main/java/dev/johnoreilly/confetti/ui/ConfettiAppState.kt
shows nav rail now on phone in landscape
> update logic for when to show nav rail

- compose-desktop/build.gradle.kts
> update Compose Desktop to v1.4.0-rc03

- shared/src/mobileMain/kotlin/dev/johnoreilly/confetti/auth/Authentication.kt
#fixes https://github.com/joreilly/Confetti/issues/546
> Handle auth expiry

- wearApp/src/main/java/dev/johnoreilly/confetti/wear/settings/PhoneSettingsSync.kt
App was stuck in loading state on launch, when standalone.
> Fix standalone results

- .github/workflows/android_wear_jvm.yml
- .github/workflows/backend-deploy.yml
- .github/workflows/backend-test.yml
- .github/workflows/build-apps.yml
- .github/workflows/ios.yml
- .github/workflows/update-schema.yml
No point paying for it when only currently used on Android builds
> Disable git lfs for most builds

- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/AppSettings.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/data/auth/FirebaseAuthUserRepository.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/settings/SettingsListView.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/settings/SettingsUiState.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/settings/SettingsView.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/settings/SettingsViewModel.kt
- wearApp/src/test/kotlin/dev/johnoreilly/confetti/wear/SettingsScreenTest.kt
Click on the version label enough times and extra debug is shown
> Add a developer mode

- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/ApolloClientCache.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/ConfettiRepository.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/utils/ClientQuery.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/sessiondetails/SessionDetailsUiState.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/sessiondetails/SessionDetailsView.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/sessiondetails/SessionDetailsViewModel.kt
- wearApp/src/test/kotlin/dev/johnoreilly/confetti/wear/SessionsDetailsTest.kt
- wearApp/src/test/kotlin/dev/johnoreilly/confetti/wear/screenshots/ScreenshotTest.kt
An attempt at a consistent UI approach for turning queries into StateFlow.
> Add a UIState Flow

- wearApp/src/main/java/dev/johnoreilly/confetti/wear/AppUiState.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/startup/InitialLoadingView.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/startup/navigation/SplashNavigation.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/ui/ConfettiApp.kt
The auth changes in https://github.com/joreilly/Confetti/pull/557/files conflicted with the startup changes.
> Fix initial app loading state

- androidApp/src/main/java/dev/johnoreilly/confetti/settings/SettingsRoute.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/settings/SettingsViewModel.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/settings/navigation/SettingsNavigation.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/ui/ConfettiApp.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/ui/ConfettiAppState.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/ui/ConfettiScaffold.kt
- androidApp/src/main/res/values/strings.xml
Turn settings into a destination and add dev settings by clicking 8 times on the version.
Not much inside these settings yet but more will come.
Closes #374
> Add mobile developer options

- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/DefaultApplication.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/ApolloClientCache.kt
It's pretty bare bones but hopefully it'll allow to recover from expired tokens.
> Add basic token refresh logic

- wearApp/src/main/java/dev/johnoreilly/confetti/wear/startup/navigation/StartHomeNavigation.kt
The scrollable dsl wires up RSB, position indicator and time text.
> Fix scrollable of home

- androidApp/src/main/java/dev/johnoreilly/confetti/di/AppModule.kt
- shared/src/androidMain/kotlin/dev/johnoreilly/confetti/di/KoinAndroid.kt
- shared/src/androidMain/kotlin/dev/johnoreilly/confetti/work/RefreshWorker.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/work/ConferenceSetting.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/conferences/ConferencesViewModel.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/di/AppModule.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/settings/SettingsViewModel.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/work/WearConferenceSetting.kt
Was trying to run too often, would be running every 15 minutes while charging.
Don't run when user selects a conference, as we are about to do that anyway.
> Improve the Wear refresh logic

- androidApp/src/main/java/dev/johnoreilly/confetti/sessiondetails/SessionDetailsView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/sessiondetails/navigation/SessionDetailsDestination.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/sessions/SessionListView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/ui/Bookmark.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/ui/ConfettiApp.kt
- shared/src/mobileMain/kotlin/dev/johnoreilly/confetti/SessionDetailsViewModel.kt
This PR adds bookmark capability on the sessions details screen for Android. Solving part of  #405 
https://user-images.githubusercontent.com/45492687/231000299-fc7c7508-286e-4961-b5a5-31b66bd0de1d.mp4
> Add bookmarks to session details screen

- wearApp/src/main/java/dev/johnoreilly/confetti/wear/MainActivity.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/sessions/navigation/sessionsDestination.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/tile/CurrentSessionsTileRenderer.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/tile/CurrentSessionsTileService.kt
- wearApp/src/test/kotlin/dev/johnoreilly/confetti/wear/app/NavigationTest.kt
Instead of the clumsy launch action intents, use a LoadAction with a partial uri.
> Improve Tile service links

- .github/workflows/backend-deploy.yml
See the failure in https://github.com/Goooler/Confetti/actions/runs/4689932575/jobs/8312328899.
> Disable deploy job in forks

- androidApp/src/main/java/dev/johnoreilly/confetti/account/AccountIcon.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/account/SignInView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/conferences/ConferencesView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/search/SearchView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/settings/SettingsRoute.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/speakerdetails/SpeakerDetailsView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/ui/ErrorView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/ui/SigninDialog.kt
- androidApp/src/main/res/values-fr/strings.xml
- androidApp/src/main/res/values/strings.xml
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/bookmarks/BookmarksScreen.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/components/SessionCard.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/home/HomeScreen.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/settings/SettingsListView.kt
- wearApp/src/main/res/values-fr/strings.xml
- wearApp/src/main/res/values/strings.xml
I might have missed a few hardcoded strings there and there, will fix them along the way.
> Initial stab at french localization

- androidApp/src/main/res/values-fr/strings.xml
- wearApp/src/main/res/values-fr/strings.xml
Feedbacks from https://github.com/joreilly/Confetti/pull/629#pullrequestreview-1394565511
> FR Localization follow up

- wearApp/snapshot/SessionCardTest/sessionCardManySpeakers.png
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/components/SessionCard.kt
- wearApp/src/test/kotlin/dev/johnoreilly/confetti/wear/components/SessionCardTest.kt
#fixes https://github.com/joreilly/Confetti/issues/625
> Fix speaker layout in session card

- androidApp/src/main/java/dev/johnoreilly/confetti/ui/ConfettiScaffold.kt
- fastlane/Fastfile
> compose title layout updates

- androidApp/proguard-rules.pro
Fixes Google SignIn
see https://github.com/firebase/firebase-android-sdk/issues/2124
> Make Firebase work with AGP 8 and R8 full mode

- iosApp/iosApp/ConfettiApp.swift
- iosApp/iosApp/Sessions/SessionListView.swift
> use NavigationSplitView

- androidApp/build.gradle.kts
- androidApp/src/main/java/dev/johnoreilly/confetti/auto/sessions/SessionsScreen.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/auto/sessions/details/SessionDetailsScreen.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/auto/speakers/SpeakersScreen.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/auto/speakers/details/SpeakerDetailsScreen.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/auto/utils/AutoImageData.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/auto/utils/AutoUtils.kt
- gradle/libs.versions.toml
- Reuse the coil image cache
- Avoid side effects writing to image Map, and use updates to Flow instead.
> Reuse the Coil image cache for Auto

- androidApp/src/main/AndroidManifest.xml
Lets see if we can finally have it approved 🙂
> Added MAP_TEMPLATES permission (required for POI category)

- androidApp/src/main/java/dev/johnoreilly/confetti/auto/bookmarks/BookmarksScreen.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/auto/conferences/ConferencesScreen.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/auto/search/SearchScreen.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/auto/sessions/SessionsScreen.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/auto/signin/SignInScreen.kt
Use ViewModel Flows and stateIn consistently
> Auto cleanup

- androidApp/src/main/java/dev/johnoreilly/confetti/auto/bookmarks/BookmarksScreen.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/auto/search/SearchScreen.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/auto/sessions/SessionsScreen.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/auto/sessions/details/SessionDetailsScreen.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/auto/speakers/SpeakersScreen.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/bookmarks/BookmarksRoute.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/di/AppModule.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/search/SearchRoute.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/sessions/SessionsRoute.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/speakers/SpeakerView.kt
- iosApp/ConfettiTests/ConfettiTests.swift
- iosApp/iosApp/ConfettiApp.swift
- shared/src/mobileMain/kotlin/dev/johnoreilly/confetti/BookmarksViewModel.kt
- shared/src/mobileMain/kotlin/dev/johnoreilly/confetti/SearchViewModel.kt
- shared/src/mobileMain/kotlin/dev/johnoreilly/confetti/SessionsViewModel.kt
- shared/src/mobileMain/kotlin/dev/johnoreilly/confetti/SessionsViewModelParams.kt
- shared/src/mobileMain/kotlin/dev/johnoreilly/confetti/SpeakersViewModel.kt
> Assist Injection in SessionsViewModel & SpeakersViewModel

- iosApp/iosApp/Sessions/SessionSpeakerInfo.swift
Fixes https://github.com/joreilly/Confetti/issues/668
> fix crash on iOS when social url is null

- wearApp/src/main/java/dev/johnoreilly/confetti/wear/complication/NextSessionComplicationService.kt
From https://b.corp.google.com/issues/277700155#comment14
> Fix complication launching

- androidApp/src/main/java/dev/johnoreilly/confetti/sessiondetails/SessionDetailsView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/speakerdetails/SpeakerDetailsView.kt
- iosApp/iosApp/Sessions/SessionDetailsView.swift
- iosApp/iosApp/Sessions/SessionSpeakerInfo.swift
- iosApp/iosApp/Speakers/SpeakerDetailsView.swift
As requested #667 , it enables the user to copy texts from Sessions and Speakers
Now on Session Details View is possible to copy the following:
- Title
- Description
- Speaker details
Now on Speaker Details View is possible to copy the following:
- Name
- Tagline
- Bio
> Enable text copy on Session Details and Speaker Details

- androidApp/src/main/java/dev/johnoreilly/confetti/account/SignInView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/auto/signin/SignInScreen.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/ui/ConfettiScaffold.kt
- gradle.properties
Signing out from Firebase does not sign out of Google so next time you would try to sign in you wouldn't be able to change Google accounts if needed
> Sign out: also sign out from Google account

- wearApp/proguard-benchmark.pro
- wearApp/proguard-rules.pro
Follow up to https://github.com/joreilly/Confetti/pull/647#issuecomment-1555032551
> Fix proguard config for Wear

- backend/datastore/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/datastore/ConferenceId.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/Main.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/TechConnection.kt
https://flutterconnection.io/
https://reactnativeconnection.io/
> Add Tech Connection conferences

- wearApp/build.gradle.kts
Otherwise Firebase gives an error in debug mode
> Explicitly setting isMinifyEnabled and isShrinkResources flags in debug mode

- backend/datastore/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/datastore/ConferenceId.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/GridTable.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/Main.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/Sessionize.kt
Have fun if you're going there !
> Add droidcon SF 2023

- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/GridTable.kt
See https://github.com/joreilly/Confetti/issues/746
> droidconSF 2023: hide breaks for now

- wearApp/src/main/java/dev/johnoreilly/confetti/wear/settings/SettingsListView.kt
- wearApp/src/main/res/values-fr/strings.xml
- wearApp/src/main/res/values/strings.xml
Extract strings from `SettingsListView`.
Enable localisation, as in https://github.com/joreilly/Confetti/pull/629
> Extract strings from SettingsListView

- compose-desktop/build.gradle.kts
- compose-desktop/src/main/kotlin/main.kt
- shared/src/jvmMain/kotlin/Main.kt
- shared/src/jvmMain/kotlin/dev/johnoreilly/confetti/di/KoinJVM.kt
- shared/src/jvmTest/kotlin/dev/johnoreilly/confetti/MainTest.kt
I didn't realize while doing [this commit](https://github.com/joreilly/Confetti/commit/fc034b5a4d0f60aad6aabe4968cefd8dcedfa8ad) that jvmMain was also used for the Compose Desktop app so it was using a fake network transport. This PR fixes that
> fix Desktop app

- androidApp/src/main/java/dev/johnoreilly/confetti/ui/HomeRoute.kt
- iosApp/iosApp.xcodeproj/project.pbxproj
- iosApp/iosApp/AppDelegate.swift
- iosApp/iosApp/HomeView.swift
- iosApp/iosApp/MultiPaneView.swift
- iosApp/iosApp/Sessions/SessionListView.swift
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/decompose/AppComponent.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/decompose/ConferenceComponent.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/decompose/HomeComponent.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/decompose/MultiPaneComponent.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/decompose/SessionsComponent.kt
> Added multi-pane layout for iOS app

- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/DevFestNantes.kt
✂️ Updates venue's image URL and venue's floor plan URL for DevFest Nantes 2023.
> ✂️ Updates venue's images.

- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/DevFestNantes.kt
Fixes floors plan url for DevFest Nantes
> Fix floors plan url for DevFest Nantes

- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/ui/SessionDetailsViewShared.kt
Here's my first contribution (ever) 😁
- The `Speakers` header matches the screen's width
- Added some spacing above the header
Closes #895
> SessionDetails UI touch up #895

- backend/datastore/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/datastore/ConferenceId.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/Main.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/Sessionize.kt
> Add Devfest Melbourne 2023

- androidApp/src/main/java/dev/johnoreilly/confetti/ui/HomeRoute.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/venue/VenueView.kt
- androidApp/src/main/res/values-fr/strings.xml
- androidApp/src/main/res/values/strings.xml
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/decompose/HomeComponent.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/decompose/VenueComponent.kt
> initial version of venue UI

- iosApp/iosApp.xcodeproj/project.pbxproj
- iosApp/iosApp/HomeView.swift
- iosApp/iosApp/Venue/VenueView.swift
> initial version of venue info in iOS app

- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/DevFestNantes.kt
> Update slots Devfest Nantes

- androidApp/src/main/java/dev/johnoreilly/confetti/MainActivity.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/bookmarks/BookmarksView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/ui/component/EmptyView.kt
- androidApp/src/main/res/values/strings.xml
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/complication/ComplicationUpdater.kt
> Empty bookmarkView

- androidApp/src/main/java/dev/johnoreilly/confetti/settings/SettingsRoute.kt
- androidApp/src/main/res/values-fr/strings.xml
- androidApp/src/main/res/values/strings.xml
https://github.com/joreilly/Confetti/assets/3974977/11ba47e5-c077-4b21-9697-a160de9f7ef2
> Add a link to the privacy policy in the app

- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/decompose/SessionsComponent.kt
The issue was due to `responseDatas: Channel` not emitting any values when restarted from background. And so `responseDatas.flatMapLatest { ... }` never subscribes to `watchBookmarks`. Replacing `Channel` with `MutableStateFlow` seems to fix the issue, as there is always the latest value to emit.
> Fixed bookmarks not working in SessionsComponent after staying in background for 5 seconds

- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/Sessionize.kt
Fix DevFest Stockholm 2023 image url
> DevFest Stockholm 2023

- backend/datastore/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/datastore/ConferenceId.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/Main.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/Sessionize.kt
> Add Devfest Sri Lanka 2023

- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/decompose/SessionsComponent.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/navigation/Config.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/sessions/ConferenceSessionsComponent.kt
Missed a stupid TODO in the decompose refactoring to reuse the mobile code.
> Fix Wear date filtering

- gradle/libs.versions.toml
Reverts joreilly/Confetti#1077
```
11:42:20.179 [main] ERROR o.s.boot.SpringApplication - Application run failed
java.lang.NoClassDefFoundError: org/yaml/snakeyaml/inspector/TagInspector
at org.springframework.boot.env.YamlPropertySourceLoader.load(YamlPropertySourceLoader.java:50)
```
> Revert "Update dependency org.springframework:spring-web to v6.1.2"

- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/resize/AvatarFetcher.kt
Temporary change for debugging
> Add some debug for image fetching

- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/DefaultApplication.kt
- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/resize/AvatarFetcher.kt
Failing on 307.
Urls like https://sessionize.com/image/93b3-400o400o1-3RzFzhm9Zkn43rrRpVjscV.jpg redirect to cache.sessionize.com
> Follow redirects in image fetching

- androidApp/src/main/java/dev/johnoreilly/confetti/venue/VenueView.kt
- iosApp/iosApp/Venue/VenueView.swift
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/decompose/VenueComponent.kt
**Note: There is no `issue` open request for this feature, so feel free to close this PR if this isn't something needed.**
This PR adds the possibility to open Google Maps when the user taps on the venue address Text.
We are using a [universal, cross-platform URL](https://developers.google.com/maps/documentation/urls/get-started) to launch Google Maps, meaning, if the Google Maps is installed on Android or iOS, the URL launches the app, otherwise, it launches it in a browser.
Android behavior:
https://github.com/joreilly/Confetti/assets/45492687/e5a41050-5d4d-438d-afd7-7a888fa84d75
iOS behavior:
https://github.com/joreilly/Confetti/assets/45492687/98d0ba35-7d6a-458d-8bdf-b37f2b71b876
> Open google maps from venue address

- .github/workflows/backend-deploy.yml
- .github/workflows/backend-test.yml
- CONTRIBUTING.md
- backend/CONTRIBUTING.md
- backend/README.md
- backend/service-graphql/build.gradle.kts
- backend/service-import/build.gradle.kts
- backend/terraform/README.md
- backend/terraform/main.tf
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/BuildImageTask.kt
- buildSrc/src/main/kotlin/BumpCloudRunRevision.kt
- buildSrc/src/main/kotlin/deploy.kt
- buildSrc/src/main/kotlin/landing.kt
- gradle/libs.versions.toml
- landing-page/build.gradle.kts
- shared/build.gradle.kts
Hopefully this removes the `You may not have more than 32 total max instances in your project.` errors and I'm also hoping it's more cost effective 🤞
> [backend] Move to Google Cloud Run

- .github/workflows/backend-test.yml
- backend/terraform/build.gradle.kts
- backend/terraform/main.tf
Also run `terraform plan` from PRs so that it fails before actually trying to deploy.
> [backend] enable startup CPU boost

- .github/workflows/backend-test.yml
- buildSrc/src/main/kotlin/BumpCloudRunRevision.kt
The secrets are not available in PRs (for good reasons I think?) so I'm not 100% sure how to run terraform there. Will revisit.
> [backend] revert running terraform in PRs

- androidApp/src/main/java/dev/johnoreilly/confetti/account/AccountIcon.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/recommendations/RecommendationsRoute.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/search/SearchView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/ui/HomeRoute.kt
- androidApp/src/main/res/values-fr/strings.xml
- androidApp/src/main/res/values/strings.xml
- compose-desktop/build.gradle.kts
- compose-desktop/src/main/kotlin/ConferenceListView.kt
- compose-desktop/src/main/kotlin/ConferenceView.kt
- compose-desktop/src/main/kotlin/main.kt
- gradle/libs.versions.toml
- iosApp/iosApp.xcodeproj/project.pbxproj
- iosApp/iosApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- iosApp/iosApp/HomeView.swift
- iosApp/iosApp/Recommendations/RecommendationsView.swift
- shared/build.gradle.kts
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/GeminiApi.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/decompose/HomeComponent.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/decompose/RecommendationsComponent.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/di/Koin.kt
Initial Gemini based functionality (only enabled if gemini api key provided).  On mobile it recommends talks for particular conference based on topic....on desktop there's free entry of query to run for the conference.
> initial gemini/recommendations functionality

- backend/service-graphql/build.gradle.kts
- gradle/libs.versions.toml
Looks losely related to https://github.com/database-rider/database-rider/issues/575
> Force snakeyaml 2.0 in the classpath

- .gitignore
Getting some annoying local diffs
> Ignore kotlin metadata

- androidApp/src/main/java/dev/johnoreilly/confetti/conferences/ConferencesView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/ui/ConferenceRoute.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/ui/component/ConfettiHeader.kt
- compose-desktop/src/main/kotlin/ConferenceView.kt
- fastlane/Fastfile
- shared/build.gradle.kts
- shared/src/commonMain/graphql/Queries.graphql
- shared/src/commonMain/graphql/schema.graphqls
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/AppSettings.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/ConfettiRepository.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/decompose/AppComponent.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/decompose/ConferenceComponent.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/utils/DateUtils.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/navigation/Routing.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/preview/TestFixtures.kt
Initial client side per conference theme color changes
> conference colour

- .github/workflows/fixes.yml
Manual workflow to trigger updating screenshots on a branch (not PR).
Can be run from https://github.com/yschimke/Confetti/actions/workflows/fixes.yml (change repo owner)
> Screenshot fixes

- iosApp/iosApp/ConferenceView.swift
- iosApp/iosApp/ConferencesView.swift
- iosApp/iosApp/MultiPaneView.swift
- iosApp/iosApp/Sessions/SessionDetailsView.swift
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/ui/ConferenceListView.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/ui/ConferenceMaterialTheme.kt
- shared/src/iosMain/kotlin/dev/johnoreilly/confetti/ui/SharedViewControllers.kt
Sharing Compose conference screen with iOS now and also passing conference theme colour for session details screen so far on iOS.
> iOS ui updates

- gradle/libs.versions.toml
- wearApp/build.gradle.kts
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/tile/CurrentSessionsTileRenderer.kt
> Improve tile layout

- landing-page/public/.well-known/assetlinks.json
1st is debug keystore, 2nd is release local keystore, 3rd is Google signing keystore for AABs
Thanks @joreilly 🙏
> .well-known: add Release fingerprints

- backend/terraform/main.tf
- landing-page/public/404.html
It took all my CSS skills to build 😅
> Add 404 page

- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/Sessionize.kt
Doesn't feel great to have to make a new PR for this. One day, we'll have this wasm backoffice management website 😄 . One day...
> Add Android Makers 2024 sponsors

- backend/datastore/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/datastore/DataStore.kt
- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/DefaultApplication.kt
- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/firebase.kt
- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/graphql/DataSource.kt
- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/graphql/DataStoreDataSource.kt
- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/graphql/TestDataSource.kt
- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/graphql/model.kt
Might be required for Data safety
> Add Mutation.deleteAccount

- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/Sessionize.kt
The service sessions are only available in the "GridSmart" view of sessionize so use that in addition to the "regular" view.
> AM2024: Add service sessions

- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/Sessionize.kt
Logos are now hosted in Cloud Storage. Many Thanks @enthuan for the logos!
> Add all dark mode logos

- backend/service-graphql/src/main/appengine/app.yaml
- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/DefaultApplication.kt
Something's wrong, investigating...
This reverts commit e434eab3ba61f444af929686e7975fe1f16288fa.
> Revert "cleanup the spring boot configuration"

- shared/src/mobileMain/kotlin/dev/johnoreilly/confetti/auth/Authentication.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/settings/SettingsComponent.kt
See https://github.com/joreilly/Confetti/issues/1309
> Robustify getIdToken

- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/graphql/model.kt
Many thanks @brunohensel for catching this 🙏
> Remove hardcoded 100 limit

- androidApp/src/main/java/dev/johnoreilly/confetti/account/SignIn.kt
> Fixed login with Google failing on fresh install.

- backend/datastore/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/datastore/ConferenceId.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/Main.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/Sessionize.kt
I forgot to update the id. Should be all good now
> Add droidcon Berlin 2/2

- androidApp/src/main/java/dev/johnoreilly/confetti/MainActivity.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/sessions/SessionListView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/ui/HomeScaffold.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/ui/Utils.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/ui/SessionListView.kt
* Add collapsing toolbar on home screen;
* Handle collapsing toolbar glitch when switching betwen pages and flinging the nested list.
https://github.com/joreilly/Confetti/assets/4348197/d0426059-6cd4-4da4-85e0-e8cc6d2d0f45
> Collapsing Toolbar

- androidApp/src/main/java/dev/johnoreilly/confetti/bookmarks/BookmarksRoute.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/recommendations/RecommendationsRoute.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/search/SearchRoute.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/sessions/SessionsRoute.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/speakers/SpeakerView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/ui/HomeRoute.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/ui/HomeScaffold.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/venue/VenueView.kt
> Move menu to left of the toolbar

- iosApp/iosApp/HomeView.swift
Improve the layout on iOS
Before:
After this change:
> Equally space the BottomBar items

- shared/build.gradle.kts
I updated a bit too much in https://github.com/joreilly/Confetti/pull/1389. Introspection just needs a single file.
> [Apollo] Fix introspection

- androidApp/src/main/java/dev/johnoreilly/confetti/MainActivity.kt
|--------|--------|
| ![before](https://github.com/user-attachments/assets/cec58506-ba3b-4f35-8817-8ca4f4d31400) | ![after](https://github.com/user-attachments/assets/7047a39b-9d75-49a3-87e9-c334fcc3b743) |
> Fix edge-to-edge on three-button nav bar

- gradle/libs.versions.toml
This is what I get for testing in production!
> Fix deploying the backend

- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/DevFestNantes.kt
Add missing base url to speaker's photo url.
> fix: devfestnantes2024 speaker's photo url.

- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/DevFestNantes.kt
Change speakers photo folder changed to static .
> fix: DevFestNantes2024 speakers photos moved to static folder

- iosApp/GoogleService-Info.plist
- iosApp/iosApp.xcodeproj/project.pbxproj
- iosApp/iosApp/AppDelegate.swift
- iosApp/iosApp/Authentication.swift
- iosApp/iosApp/ConferenceView.swift
- iosApp/iosApp/ConfettiApp.swift
- iosApp/iosApp/HomeView.swift
- iosApp/iosApp/Info.plist
- iosApp/iosApp/Login.swift
- iosApp/iosApp/Recommendations/RecommendationsView.swift
- iosApp/iosApp/Sessions/SessionDetailsView.swift
- iosApp/iosApp/iOSApp.swift
Initial version....still need to plumb down so shared components know the user details
> google sign in on iOS

- iosApp/iosApp/ConferenceView.swift
- iosApp/iosApp/ConfettiApp.swift
- iosApp/iosApp/HomeView.swift
> show profile image of logged in user in toolbar

- gradle/libs.versions.toml
- iosApp/iosApp/AppDelegate.swift
- iosApp/iosApp/ConfettiApp.swift
- iosApp/iosApp/iOSApp.swift
- shared/build.gradle.kts
- shared/src/androidMain/kotlin/dev/johnoreilly/confetti/ui/PredictiveBackAnimation.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/ui/App.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/ui/PredictiveBackAnimation.kt
- shared/src/iosMain/kotlin/dev/johnoreilly/confetti/ui/MainViewController.kt
- shared/src/iosMain/kotlin/dev/johnoreilly/confetti/ui/PredictiveBackAnimation.ios.kt
- shared/src/jvmMain/kotlin/dev/johnoreilly/confetti/ui/PredictiveBackAnimation.kt
- shared/src/wasmJsMain/kotlin/dev/johnoreilly/confetti/ui/PredictiveBackAnimation.kt
This is how it looks like on iOS. On Android it looks the same as before it was disabled.
https://github.com/user-attachments/assets/257701c3-dab0-4720-b053-1529122d9344
> Enabled predictive back gesture on Android and iOS

- androidApp/src/main/AndroidManifest.xml
- gradle/libs.versions.toml
- shared/src/androidMain/kotlin/dev/johnoreilly/confetti/di/KoinAndroid.kt
- shared/src/androidMain/kotlin/dev/johnoreilly/confetti/work/SessionNotificationSender.kt
- shared/src/androidMain/kotlin/dev/johnoreilly/confetti/work/SessionNotificationWorker.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/decompose/AppComponent.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/decompose/SettingsComponent.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/ui/settings/SettingsUI.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/work/NotificationSender.kt
- wearApp/build.gradle.kts
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/ConfettiApplication.kt
Allow forcing sending notifications with a widened range for testing.
> Add developer setting button to send notifications

- wearApp/snapshot/BookmarksTest/bookmarksEmpty[GenericLargeRound].png
- wearApp/snapshot/BookmarksTest/bookmarksEmpty[GenericSmallRound].png
- wearApp/snapshot/BookmarksTest/bookmarksEmpty[GooglePixelWatchLargeFont].png
- wearApp/snapshot/BookmarksTest/bookmarksEmpty[GooglePixelWatch].png
- wearApp/snapshot/BookmarksTest/bookmarksEmpty[MobvoiTicWatchPro5].png
- wearApp/snapshot/BookmarksTest/bookmarksEmpty[SamsungGalaxyWatch5].png
- wearApp/snapshot/BookmarksTest/bookmarksEmpty[SamsungGalaxyWatch6SmallFont].png
- wearApp/snapshot/BookmarksTest/bookmarksEmpty[SamsungGalaxyWatch6].png
- wearApp/snapshot/BookmarksTest/bookmarksError[GenericLargeRound].png
- wearApp/snapshot/BookmarksTest/bookmarksError[GenericSmallRound].png
- wearApp/snapshot/BookmarksTest/bookmarksError[GooglePixelWatchLargeFont].png
- wearApp/snapshot/BookmarksTest/bookmarksError[GooglePixelWatch].png
- wearApp/snapshot/BookmarksTest/bookmarksError[MobvoiTicWatchPro5].png
- wearApp/snapshot/BookmarksTest/bookmarksError[SamsungGalaxyWatch5].png
- wearApp/snapshot/BookmarksTest/bookmarksError[SamsungGalaxyWatch6SmallFont].png
- wearApp/snapshot/BookmarksTest/bookmarksError[SamsungGalaxyWatch6].png
- wearApp/snapshot/BookmarksTest/bookmarksLoading[GenericLargeRound].png
- wearApp/snapshot/BookmarksTest/bookmarksLoading[GenericSmallRound].png
- wearApp/snapshot/BookmarksTest/bookmarksLoading[GooglePixelWatchLargeFont].png
- wearApp/snapshot/BookmarksTest/bookmarksLoading[GooglePixelWatch].png
- wearApp/snapshot/BookmarksTest/bookmarksLoading[MobvoiTicWatchPro5].png
- wearApp/snapshot/BookmarksTest/bookmarksLoading[SamsungGalaxyWatch5].png
- wearApp/snapshot/BookmarksTest/bookmarksLoading[SamsungGalaxyWatch6SmallFont].png
- wearApp/snapshot/BookmarksTest/bookmarksLoading[SamsungGalaxyWatch6].png
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/bookmarks/BookmarksComponent.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/bookmarks/BookmarksScreen.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/components/SessionCard.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/home/HomeScreen.kt
- wearApp/src/test/kotlin/dev/johnoreilly/confetti/wear/BookmarksTest.kt
This commit adds previews for loading and error states to the Bookmarks screen.
Those UIs don't currently exist.
> Add Bookmarks Loading and Error states

- gradle/libs.versions.toml
- shared/build.gradle.kts
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/decompose/SearchComponent.kt
https://github.com/user-attachments/assets/c562a2bd-099d-4928-82ea-1d274936b926
> Ignore diacritics/accents in search when input doesn't contain them
