joreilly/Confetti

- .github/workflows/update-schema.yml
- .gitignore
- build.gradle.kts
- buildSrc/src/main/java/Dependencies.kt
- server/build.gradle.kts
- server/src/main/kotlin/fr/androidmakers/server/DefaultApplication.kt
- shared/build.gradle.kts
The backend will now upload the SDL to the registry every boot. 
The Github Action will download the SDL from the registry instead of introspection.
This way, we'll get the `@deprecated` usage propagated to the schema 🙌
> :atom: Configure Apollo Studio

- .github/workflows/backend-deploy.yml
The last deploy failed and the new schema wasn't uploaded to Studio. This PR fixes that so that the next automated "update GraphQL schema" PR returns the latests schema
> Fix Apollo Key path

- .github/workflows/backend-deploy.yml
The previous PR did not trigger a CI run because no change was in `backend` 🤦 . This PR makes sure that changes in the yaml themselves trigger a new workflow run.
> include .github/workflows

- iosApp/iosApp.xcodeproj/xcshareddata/xcschemes/iosApp.xcscheme
XCode 14 added this folder and [it looks like it should be added to source control](https://stackoverflow.com/questions/53034303/should-xcshareddata-be-checked-into-git-repo-for-xcode-project). It contains a scheme to run the iosApp on the simulator so far
> Add xcshareddata

- androidApp/src/main/java/dev/johnoreilly/confetti/ConfettiViewModel.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/sessiondetails/SessionDetailsViewModel.kt
- iosApp/iosApp/ConfettiViewModel.swift
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/ConfettiRepository.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/di/Koin.kt
- Use CacheAndNetwork instead of the default CacheFirst for watch()
- Do no trigger two network requests at startup
- remove logging interceptor
> A few fixes

- backend/service-graphql/src/main/appengine/app.yaml
In prevision of DevFest Nantes next week, allow to use a bit more resources if needed
> GraphQL backend: increase max instances

- androidApp/src/main/java/dev/johnoreilly/confetti/MainActivity.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/conferences/ConferencesView.kt
The "Choose Conference" screen didn't have a surface background on the first run. I also tweaked its UI a tiny a bit.
Before:
After:
> Improve initial "Choose Conferences" screen on dark mode

- shared/src/androidMain/kotlin/dev/johnoreilly/confetti/utils/AndroidDateTimeFormatter.kt
See https://issuetracker.google.com/issues/260755411
This was needed for AGP 8.0 but we don't use it yet and there's a fix in `8.0.0-alpha10` anyways
> Remove lint + AGP8 workaround

- backend/datastore/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/datastore/DataStore.kt
- backend/datastore/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/datastore/model.kt
- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/DefaultApplication.kt
- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/graphql/DataStoreDataSource.kt
- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/graphql/model.kt
- backend/service-import/README.md
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/Main.kt
The default is newest first. Can be changed with 
```graphql
{
conferences(orderBy: {field: DAYS, direction: ASCENDING}) {
id
days
name
}
}
```
> Add orderBy argument to conferences

- androidApp/src/main/java/dev/johnoreilly/confetti/ConfettiApplication.kt
- backend/service-import/build.gradle.kts
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/DevFestNantes.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/DroidConSF.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/FrenchKit.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/GraphQLSummit.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/Main.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/Sessionize.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/utils.kt
- gradle/libs.versions.toml
- shared/build.gradle.kts
- shared/src/androidMain/kotlin/dev/johnoreilly/confetti/di/KoinAndroid.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/ConfettiRepository.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/di/Koin.kt
- shared/src/iosMain/kotlin/dev/johnoreilly/confetti/di/KoiniOS.kt
- shared/src/jvmMain/kotlin/dev/johnoreilly/confetti/di/KoinJVM.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/ConfettiApplication.kt
For discussion - happy to close if not in scope.  But you seem to use modern versions a lot.
Uses a single instance of OkHttp across Apollo and Coil.  Uses clean coroutines code in all places also, and happy eyeballs to speed up IPv6/IPv4 related issues.
> Use OkHttp 5 - coroutines and happy eyeballs

- gradle/libs.versions.toml
- wearApp/build.gradle.kts
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/conferences/ConferencesView.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/sessions/sessionsListView.kt
- wearBenchmark/src/main/java/dev/johnoreilly/confetti/benchmark/ColdStartupBenchmark.kt
Meaningless numbers from emulator
```
ColdStartupBenchmark_startup
timeToFullDisplayMs   min 519.0,   median 533.3,   max 834.0
timeToInitialDisplayMs   min 445.3,   median 460.3,   max 479.9
Traces: Iteration 0 1 2 3 4
```
> Add timeToFullDisplayMs metric

- androidApp/src/main/java/dev/johnoreilly/confetti/di/AppModule.kt
- shared/build.gradle.kts
- shared/src/commonMain/graphql/Queries.graphql
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/ApolloClientCache.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/ConfettiRepository.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/di/Koin.kt
- shared/src/jvmMain/kotlin/Main.kt
- shared/src/jvmMain/kotlin/dev/johnoreilly/confetti/di/KoinJVM.kt
- shared/src/jvmTest/kotlin/dev/johnoreilly/confetti/MainTest.kt
- shared/src/mobileMain/kotlin/dev/johnoreilly/confetti/navigation/SessionDetailsKey.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/MainActivity.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/di/AppModule.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/home/homeView.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/home/navigation/homeDestination.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/sessiondetails/SessionDetailsViewModel.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/sessiondetails/navigation/SessionDetailsDestination.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/sessions/navigation/sessionsDestination.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/sessions/sessionView.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/ui/ConfettiApp.kt
Splitting up ConfettiViewModel, use targetted specific queries.
This isn't very simple yet. Plan
1) Demonstrate this approach incrementally on Wear
a) SessionDetails (this)
b) Session
c) Conference Day
d) Conference
2) Apply to android also
3) Delete ConfettiViewModel, ensure clean navigation with conference in all paths.
Need to land after https://github.com/joreilly/Confetti/pull/255
> Split up SessionDetail ViewModel to use specific query.

- shared/src/commonMain/graphql/Queries.graphql
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/ConfettiRepository.kt
- shared/src/mobileMain/kotlin/dev/johnoreilly/confetti/navigation/ConferenceDayKey.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/MainActivity.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/home/homeView.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/home/navigation/homeDestination.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/sessiondetails/SessionDetailsViewModel.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/sessiondetails/navigation/SessionDetailsDestination.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/sessions/SessionsViewModel.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/sessions/navigation/sessionsDestination.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/sessions/sessionView.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/sessions/sessionsListView.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/ui/ConfettiApp.kt
Step 2.
I suspect caching for this won't make sense until I stop using ConfettiViewModel with it's uber query, and change to a refresh that queries Sessions, Rooms and Speakers in matching queries.
But pulling a thread and seeing where it goes.
> Split up Sessions Screen ViewModel.

- backend/datastore/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/datastore/ConferenceId.kt
- backend/datastore/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/datastore/DataStore.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/Main.kt
- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/Sessionize.kt
We're a bit early because none of the sessions are scheduled yet and we filter them out.
We should have a way in the API to get "unfiltered" sessions
> Prepare for AndroidMakers

- shared/src/commonMain/graphql/Queries.graphql
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/AppSettings.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/ConfettiRepository.kt
- wearApp/src/androidTest/java/dev/johnoreilly/confetti/wear/ScreenshotTest.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/conferences/ConferencesUiState.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/conferences/ConferencesView.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/conferences/ConferencesViewModel.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/di/AppModule.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/home/HomeUiState.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/home/HomeViewModel.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/home/homeListView.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/home/homeView.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/sessiondetails/SessionDetailsUiState.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/sessiondetails/SessionDetailsView.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/sessiondetails/SessionDetailsViewModel.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/sessions/SessionCard.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/sessions/SessionsUiState.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/sessions/SessionsViewModel.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/sessions/navigation/sessionsDestination.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/sessions/sessionsListView.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/settings/SettingsListView.kt
Avoid using `dataAssertNoErrors`. Instead have a model with Loading, Success, Error.
Follow up work to improve errors and loading.
> Introduce UI State models

- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/ConfettiRepository.kt
- shared/src/jvmMain/kotlin/Main.kt
- shared/src/mobileMain/kotlin/dev/johnoreilly/confetti/ConfettiViewModel.kt
- shared/src/mobileMain/kotlin/dev/johnoreilly/confetti/JobConferenceRefresh.kt
Remove state from ConfettiRepository.
It does cause a delay after switching conference, while refresh is happening.
> Simplify ConfettiRepository

- androidApp/src/main/java/dev/johnoreilly/confetti/di/AppModule.kt
- shared/src/androidMain/kotlin/dev/johnoreilly/confetti/di/KoinAndroid.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/ApolloClientCache.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/di/Koin.kt
- shared/src/iosMain/kotlin/dev/johnoreilly/confetti/di/KoiniOS.kt
- shared/src/jvmMain/kotlin/dev/johnoreilly/confetti/di/KoinJVM.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/di/AppModule.kt
Koin's constructor DSL reduces boilerplate by:
1. Removing the need to directly call `get()` for each parameter;
2. Allowing classes to evolve and change their constructor without requiring them to change their binding manually;
3. The previous two points reduce the chance of human error, as there is less code to update once a class's constructor changes.
For more details about the Constructor DSL, please refer to: https://insert-koin.io/docs/reference/koin-core/dsl-update
> Use Koin's Constructor DSL

- androidApp/src/main/java/dev/johnoreilly/confetti/ui/ConfettiScaffold.kt
The default behaviour is to keep top bar always visible. However, if NavRail is not visible (i.e., phones), we can collapse the top bar while scrolling to save visible space and let the user focus on the screen's content.
| TopBar Expanded | TopBar Collapsed |
|---|---|
| ![Screenshot_1679245606](https://user-images.githubusercontent.com/4348197/226192679-71904921-1cc8-4ba0-b8bb-976611d59578.png) | ![Screenshot_1679245614](https://user-images.githubusercontent.com/4348197/226192686-2406c37b-18a6-4a2c-9394-86d5fcb4169b.png) |
| ![Screenshot_1679245619](https://user-images.githubusercontent.com/4348197/226192685-5e21511f-b6f8-4c4a-9d4c-4a024229b527.png) | ![Screenshot_1679245623](https://user-images.githubusercontent.com/4348197/226192684-8f14e2f4-896d-4c27-b455-f735d020ae9b.png) |
> Collapse top-bar while scrolling

- androidApp/src/main/java/dev/johnoreilly/confetti/sessions/SessionListView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/utils/LocalDateTime.kt
* Instead of printing the `LocalDate` without any format, fallbacks to use the `FormatStyle.MEDIUM`.
> Format date tabs

- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/CacheControlInstrumentation.kt
- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/DefaultApplication.kt
Turns out [the CDN wasn't looking at Cache-Control headers](https://console.cloud.google.com/net-services/cdn/backendService/edit/backend-graphql/loadbalancer1?project=confetti-349319):
I've changed the header so that now the CDN always looks at the origin headers (option #2 above) and therefore we need to send something all the time. See https://github.com/joreilly/Confetti/issues/307
> GraphQL: always send cache-control values

- landing-page/public/index.html
- landing-page/public/playground/index.html
- landing-page/public/sandbox/index.html
This way you can choose your GraphQL IDE of choice
> Add Apollo Sandbox and GraphQL playground as alternate IDEs

- androidApp/src/main/java/dev/johnoreilly/confetti/account/AccountIcon.kt
Firstly, thanks for a super cool and inspiring project! 👏  A lot of cool stuff to learn for me here! :) 
In this PR I have moved the ViewModel one level up from the `AccountIcon` in an effort to try to make the `AccountIcon` composable more stateless so that it is easier to make preview functions for it.
I was not 100% sure which approach was the best for this.  I was first thinking to just pass the UIState object as a parameter. Then I thought that it might be even easier to mock if I just pass the boolean types and the user object. 
I also added a preview for light and dark theme with a background so that it was a bit easier to see.
resolves #375
> Make AccountIcon composable less stateful

- compose-desktop/src/main/kotlin/main.kt
Just showing date/time for every session in absence of way right now to select date.
> compose for dekstop: add date/time

- androidApp/src/main/java/dev/johnoreilly/confetti/sessions/SessionsView.kt
- iosApp/iosApp/ConfettiApp.swift
- iosApp/iosApp/Sessions/SessionListView.swift
- shared/src/mobileMain/kotlin/dev/johnoreilly/confetti/SessionsViewModel.kt
Similar to Android right now (as expected) in that it still shows empty hours....but hopefully we can resolve that separately in shared view model for all clients. cc @marcellogalhardo 
Fixes https://github.com/joreilly/Confetti/issues/421
> also support search in SwiftUI client

- androidApp/src/main/java/dev/johnoreilly/confetti/ui/ConfettiScaffold.kt
- shared/src/mobileMain/kotlin/dev/johnoreilly/confetti/SessionsViewModel.kt
* ~Search is now always visible.~
* Search removes any empty dates, they are unnecessary clusters.
* Pressing back now closes the search, before closing the app.
* Account action moved to the right side of the top bar.
~@joreilly + @martinbonnin I'm not sure how much I like the new search compared with the previous one (and there is no animation now), but it will make it easier to include a filter action in the future (on the right side of the account).~
EDIT: I have dropped the new Search UI for now, we can discuss it separately.
> Improve Search experience

- androidApp/src/main/java/dev/johnoreilly/confetti/account/AccountIcon.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/account/AccountViewModel.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/account/SignInView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/account/authIntent.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/di/AppModule.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/search/SearchRoute.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/search/SearchView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/sessions/SessionListView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/sessions/SessionsRoute.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/sessions/navigation/SessionsDestination.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/speakers/SpeakerView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/ui/ConfettiScaffold.kt
- iosApp/ConfettiTests/ConfettiTests.swift
- iosApp/iosApp/ConfettiApp.swift
- shared/src/androidMain/kotlin/dev/johnoreilly/confetti/di/KoinAndroid.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/ApolloClientCache.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/ConfettiRepository.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/di/Koin.kt
- shared/src/iosMain/kotlin/dev/johnoreilly/confetti/di/KoiniOS.kt
- shared/src/jvmMain/kotlin/dev/johnoreilly/confetti/di/KoinJVM.kt
- shared/src/mobileMain/kotlin/dev/johnoreilly/confetti/SearchViewModel.kt
- shared/src/mobileMain/kotlin/dev/johnoreilly/confetti/SessionsViewModel.kt
- shared/src/mobileMain/kotlin/dev/johnoreilly/confetti/auth/Authentication.kt
Follow up from https://github.com/joreilly/Confetti/pull/449
This turns `User` and `Authentication` into interfaces that we can fake for tests/previews. Also fixes #450
@oas004 @yschimke let me know what you think, it passes `uid` and `tokenProvider` all the way down to the repository so now we have an `uid` parameter everywhere in addition to `conference` (but not in deeplinks). It's a bit verbose (Compose loves long lists of arguments) but at least it's correct and the bookmark state is now in-sync with the AccountIcon.
> Auth rework

- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/graphql/DataStoreDataSource.kt
- backend/service-graphql/src/main/resources/application.yml
Since the addition of Speaker.session, we were querying Datastore separately for each session and that increase the `GetConferenceData` time a lot. Cache this information to make it faster. 
Also enable playground.
> Backend: cache sessions

- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/DefaultApplication.kt
If schema reporting fails, the server should still keep serving requests
> Backend: be robust to schema reporting failures

- androidApp/src/main/AndroidManifest.xml
- androidApp/src/main/java/dev/johnoreilly/confetti/search/SearchView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/sessions/SessionListView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/speakerdetails/SpeakerDetailsView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/ui/ConfettiBottomBar.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/ui/ConfettiScaffold.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/ui/component/ConfettiHeader.kt
* Fixes the keyboard covering part of the UI.
* Automatically opens the keyboard when scrolling down the screen.
* Creates unified `ConfettiHeader` to be used across all screens.
* Fixes icon from sessions: now we use the event icon.
| Schedule | Speaker Details | Search |
|---|---|---|
|  ![Screenshot_1680381885](https://user-images.githubusercontent.com/4348197/229313658-4060a13f-f5d1-4fbc-9c8e-3d4efbb67fc7.png) | ![Screenshot_1680382510](https://user-images.githubusercontent.com/4348197/229313674-f37de9e0-bf9c-45d8-92c0-679e65c6153a.png) | ![Screenshot_1680382546](https://user-images.githubusercontent.com/4348197/229313684-669bfd1a-329a-4d05-acdd-0bd9876621dc.png) |
Scrollable Keyboard Animation:
[keyboard_ime_anim.webm](https://user-images.githubusercontent.com/4348197/229313704-39c455 …
> Fix Keyboard and Improve Section Headers

- androidApp/src/main/java/dev/johnoreilly/confetti/bookmarks/BookmarksRoute.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/bookmarks/BookmarksView.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/utils/DateService.kt
- shared/src/mobileMain/kotlin/dev/johnoreilly/confetti/BookmarksViewModel.kt
* Add past/upcoming tabs to bookmarks.
* Filter automatically based on the current time, refreshed every 5 minutes - it seemed reasonable, but we can fine-tune it as we wish.
Issues: the tab text color is different between sessions and bookmarks, we will need to fix it.
| Past | Upcoming |
|---|---|
| ![Screenshot_1680445258](https://user-images.githubusercontent.com/4348197/229360188-2f22175c-6020-4fb5-8eed-5f0c792a6e96.png) | ![Screenshot_1680445261](https://user-images.githubusercontent.com/4348197/229360198-7f1f5e0c-107a-497b-8a3d-56454047036e.png) |
> Add past/upcoming filters to bookmarks

- androidApp/src/main/java/dev/johnoreilly/confetti/ui/component/SocialIcon.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/ui/component/SocialIcon.kt
Also made it a bit less transparent
<table>
<tr><td>Before</td><td>After</td></tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
> Fix social icon tint when system ui is light, but app is dark

- androidApp/src/main/java/dev/johnoreilly/confetti/sessiondetails/SessionDetailsView.kt
Added the time and room for to be displayed in the session details. 
This should resolve #487 
I used `labelLarge` for these texts. Not quite sure if that is correct. According to M3 docs, you can use that for small texts in text bodys like captions (https://m3.material.io/styles/typography/applying-type#af6eb002-9cbb-4b64-bce6-1315d2252364). I can change it up if that is preferred. Maybe it's a bit small. Here is how it looks
Android Phone
Android Tablet
> Show time and room in session details

- androidApp/src/main/java/dev/johnoreilly/confetti/sessiondetails/SessionDetailsView.kt
The formatting here was different from what's displayed for the session overview screen
For sessions starting 13:00 this was showing 01:00 in the details part but 13:00 in the overview part, so I changed it to match the overview.
> Fix session details time format

- androidApp/src/main/AndroidManifest.xml
We're using androidx.navigation already, so we can opt in and get this feature for free for those phones that have opted into this flag. What do you think?
| --- | --- |
| https://user-images.githubusercontent.com/44558292/230495796-2a4365e1-3492-44ac-8fa8-af14e731625b.mp4 | https://user-images.githubusercontent.com/44558292/230495843-76716ed5-eeff-4648-b55a-67fc639d6625.mp4 |
> Enable predictive back gesture

- androidApp/src/main/java/dev/johnoreilly/confetti/sessions/SessionListGridView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/sessions/SessionListView.kt
- iosApp/iosApp/Sessions/SessionListView.swift
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/Model.kt
Partially addresses #533
Used `Icons.Default.Bolt` as a simple way to get something resembling what's in the website as discussed here https://kotlinlang.slack.com/archives/C051P2HUVKP/p1680724416100319. If we want the actual same icon as the website I wasn't sure how you'd like to bring that in so I didn't do it.
| Phone | Tablet |
| --- | --- |
| ![phone_lightning](https://user-images.githubusercontent.com/44558292/230522571-ced7f5f6-b233-4519-8161-77e9a160cd41.png) | ![tablet_lightning](https://user-images.githubusercontent.com/44558292/230522577-ec2dea6a-90d9-435d-9161-d997ce9a153b.png) |
Plus a little change in the modifier order so that the click interaction in the card spans across the entire card.
| Light mode | Dark mode |
| --- | --- |
| …
> Indicate lightning talks

- androidApp/src/main/java/dev/johnoreilly/confetti/sessions/SessionListGridView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/ui/ConfettiScaffold.kt
Make use of window insets instead, to specifically only pad that much for cases like tablets, while still making sure that in phone form factors the insets are not applied two times.
How it looked like before:
Changing from padding(80) to using insets initially changes it to this (Got some red border to indicate where the content should be):
That extra spacing is from the window insets for the navigation bar being applied again
The `consumedInsetsModifier` I added makes sure that we inform the content that the insets are already consumed. This does not happen automatically in this case since `ConfettiBottomBar` and `content()` are two separate items, and the way that the inset modifiers work is that they inform items that are children of wherever they are applied. Since now they're not …
> Fix session screen having some unnecessary bottom padding

- androidApp/src/main/java/dev/johnoreilly/confetti/sessiondetails/SessionDetailsView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/sessiondetails/SessionSpeakerInfo.kt
Following up on comment from @marcellogalhardo (https://github.com/joreilly/Confetti/pull/511#issuecomment-1497821209).  Trying to improve the ripple effect so that it is going all the way to the sides horizontally. This was to remove the pointy square feeling.
Now it looks like this:
https://user-images.githubusercontent.com/54936943/230162005-2179d00c-2f56-4bbe-8f9e-7a65e409c049.mp4
> Improve ripple on speaker view on session details

- androidApp/src/main/java/dev/johnoreilly/confetti/ui/ConfettiNavRail.kt
I basically did exactly what was done in [ConfettiBottomBar](https://github.com/joreilly/Confetti/blob/ac825360d17b8bc4063352de096059c8a7fb703e/androidApp/src/main/java/dev/johnoreilly/confetti/ui/ConfettiBottomBar.kt#L28-L32).
Not sure about the difference between `routePattern` and whatever `route(conference)` returns, but this change makes it work so all good :D
Before: can be see in this picture https://kotlinlang.slack.com/archives/C051P2HUVKP/p1680864472535699?thread_ts=1680856278.244949&cid=C051P2HUVKP
After:
> Fix nav rail not highlighting selected item

- androidApp/src/main/java/dev/johnoreilly/confetti/bookmarks/BookmarksView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/search/SearchView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/sessions/SessionListGridView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/speakers/SpeakerView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/utils/PaddingValuesExt.kt
These were adding some padding which is unnecessary. Winning a tiny bit more screen real estate 😊
| --- | --- |
| ![before_insets](https://user-images.githubusercontent.com/44558292/230598912-cd784c15-e88e-4bb1-8177-1864107347bf.png) | ![after_insets](https://user-images.githubusercontent.com/44558292/230598921-cb8ff90f-3969-4be7-a835-e8df2d02bf27.png) |
| --- | --- |
| ![before_speakers](https://user-images.githubusercontent.com/44558292/230598944-abefb6f8-0bd9-4496-8dd5-47c36d6cb418.png) | ![after_speakers](https://user-images.githubusercontent.com/44558292/230598951-b8d42201-3ec1-4132-bc40-083f63cae0f8.png) |
| --- | --- |
| ![before_search_max_scroll](https://user-images.githubusercontent.com/44558292/230599006-f5a1f58e-f120-491d …
> Going under navigation bar in the top level screens that now show navigation rail instead

- wearApp/src/main/java/dev/johnoreilly/confetti/wear/settings/PhoneSettingsSync.kt
- wearApp/src/test/kotlin/dev/johnoreilly/confetti/wear/app/NavigationTest.kt
Tests are basically manual at the moment, because they fail with a koin error if more than one is run.
> Add tests for startup navigation

- androidApp/src/main/java/dev/johnoreilly/confetti/ConfettiApplication.kt
- shared/src/androidMain/kotlin/dev/johnoreilly/confetti/work/SessionNotificationSender.kt
- shared/src/androidMain/kotlin/dev/johnoreilly/confetti/work/SessionNotificationWorker.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/utils/DateService.kt
Fixes:
* Guard added to reduce processing from `SessionNotificationWorker` was incorrect, please see [this](https://github.com/joreilly/Confetti/pull/571/commits/3670f54fc1e299f4bfc16e67a66ea0494947389f).
* WorkManager factory is failing to launch the `SessionNotificationWorker` silently. Changing `SessionNotificationWorker` to `KoinComponent` fixes the problem. Please, see [this](https://github.com/joreilly/Confetti/pull/571/commits/defe8396ac4b911ef791db7ccab34a8a2e537ca7).
* Handle different timezones when detecting upcoming sessions.
Improvements:
* Add a retry strategy to handle errors instead of returning failure directly.
* Update comments & code around `SessionNotificationWorker`.
> Fix notification not appearing

- gradle/libs.versions.toml
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/utils/ClientQuery.kt
- wearApp/build.gradle.kts
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/MainActivity.kt
- wearApp/src/test/kotlin/dev/johnoreilly/confetti/wear/SessionsDetailsTest.kt
- wearApp/src/test/kotlin/dev/johnoreilly/confetti/wear/ThemeTest.kt
- wearApp/src/test/kotlin/dev/johnoreilly/confetti/wear/app/AppTest.kt
- wearApp/src/test/kotlin/dev/johnoreilly/confetti/wear/app/BaseAppTest.kt
- wearApp/src/test/kotlin/dev/johnoreilly/confetti/wear/app/NavigationTest.kt
- wearApp/src/test/kotlin/dev/johnoreilly/confetti/wear/app/OfflineTest.kt
- wearApp/src/test/kotlin/dev/johnoreilly/confetti/wear/screenshots/FetchDataTest.kt
- wearApp/src/test/kotlin/dev/johnoreilly/confetti/wear/screenshots/ScreenshotTest.kt
The point of this is tests like
https://github.com/joreilly/Confetti/pull/580/files#diff-99ed401829d591e6c11b145b77c1035b0613dc27418c3633bf0ae6da82f9d5a5
Which should confirm real app behaviour.
> Enable wear app tests

- androidApp/src/main/java/dev/johnoreilly/confetti/sessions/SessionListView.kt
- shared/src/mobileMain/kotlin/dev/johnoreilly/confetti/SessionsViewModel.kt
* Opens session tab in the current date.
* Opens session tab in the current "time slot" (closest hour to the current hour).
For the tests, I hard coded the current result for `now`: `LocalDateTime(year = 2023, month = 4, day = 14, hour = 11, minutes = 20)`, and opened the application.
|---|---|
| ![Screenshot_1681149714](https://user-images.githubusercontent.com/4348197/230964027-2f2ab812-9d68-4fd2-ab75-fa26fc6fef7a.png) | ![Screenshot_1681149709](https://user-images.githubusercontent.com/4348197/230964061-7a329d01-4f8c-4ac4-a0b3-8524fea42369.png) |
> Opening sessions tab should show relevant talks for current date and hour

- androidApp/src/main/java/dev/johnoreilly/confetti/search/SearchView.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/sessiondetails/SessionDetailsView.kt
* Add `ConfettiHeader` to Speakers section inside Session Details.
* Improves UI and makes it consistent with other screens.
* Replace hardcoded Strings with `R.string` variants.
> Add `ConfettiHeader` to speakers section in Session Details

- shared/src/androidMain/res/drawable/ic_launcher_foreground.xml
- shared/src/androidMain/res/drawable/ic_launcher_monochrome.xml
- shared/src/androidMain/res/mipmap-anydpi-v26/ic_launcher.xml
- shared/src/androidMain/res/mipmap-anydpi-v26/ic_launcher_round.xml
- shared/src/androidMain/res/values/ic_launcher_background.xml
Took some creative liberty to add a monochrome version of the icon. I don't have a licence to sketch, so I can't open or modify the sketch file. I do have a figma source available.
This is how it looks 
Before:
After:
> Add adaptive monochrome icon

- androidApp/proguard-rules.pro
It seems that we need to add the `StaticLoggerBinder` `-dontwarn` for Ktor.
More info:
- https://youtrack.jetbrains.com/issue/KTOR-5528
> Added -dontwarn for StaticLoggerBinder to proguard-rules

- androidApp/google-services.json
- androidApp/src/main/java/dev/johnoreilly/confetti/account/SignInView.kt
- wearApp/google-services.json
This somewhat makes Google signin work again. I'm not 100% sure what happened there.
The error that was happening was `ApiException: 12500`. From [stackoverflow](https://stackoverflow.com/questions/47632035/google-sign-in-error-12500), this can be a number of things from missing support email to wrong sha1
I also put the Oauth consent screen back to "testing", which allows anyone to log in (with a warning)
From [doc](https://support.google.com/cloud/answer/10311615#publishing-status&zippy=%2Ctesting):
```
if your app requests a subset of the following: name, email address, and user profile (through the [userinfo.email, 
userinfo.profile, openid](https://developers.google.com/identity/protocols/oauth2/scopes#oauth2) scopes or their 
[OpenID Connect …
```
> Google Signin: Change the oauth client id

- androidApp/src/main/java/dev/johnoreilly/confetti/ui/Bookmark.kt
A minor UI detail that bothered me. When interacting with the bookmark icon the background is a grey rectangle. For other icons like account or share action it's a circle. The difference is that the other buttons use an `IconButton` (with a nested `Icon`) while the `Bookmark` composable only uses an icon.
Wrapped the icon(s) in the Bookmark composable with an IconButton similar to the other occurences
|---|---|
| ![bookmark-before-list](https://user-images.githubusercontent.com/1376279/234096549-a8f65020-c7f6-4b9b-81b0-5601c67717f1.png) | ![bookmark-after-list](https://user-images.githubusercontent.com/1376279/234096584-3e503bf9-c527-4b24-a357-ad6a7b554e53.png) |
| ![bookmark-before-details](https://user-images.githubusercontent.com/1376279/234096800-c1d84d81-4511-4678-b …
> Adjust bookmark icon interaction background

- androidApp/src/main/java/dev/johnoreilly/confetti/auto/speakers/SpeakersScreen.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/auto/speakers/details/SpeakerDetailsScreen.kt
Was wrongly setting the name instead of the `photoUrl`. 
Due to cache, it kept working, only on a new install I was able to replicate this.
> Fixed speakers' photo url

- androidTest/build.gradle.kts
Gradle was failing with an error without this, when called from the Apollo Kotlin IJ plugin. Not sure why we don't get any Gradle failure elsewhere 😅
> Add desugaring dependency to androidTest project

- backend/service-graphql/src/main/appengine/app.yaml
This means there will not always be an instance ready to server requests which means cold requests can have several seconds of latency but it's probably fine
> Try to reduce AppEngine costs a bit

- gradle/libs.versions.toml
- shared/build.gradle.kts
- shared/src/androidMain/kotlin/dev/johnoreilly/confetti/di/KoinAndroid.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/ApolloClientCache.kt
- shared/src/iosMain/kotlin/dev/johnoreilly/confetti/di/KoiniOS.kt
- shared/src/jvmMain/kotlin/dev/johnoreilly/confetti/di/KoinJVM.kt
This should fix the flakyness of the tests since we downgraded the class of the AppEngine instances. Cold starts can take more than 10s now (which is another problem but at not relying on the network in tests sounds better)
> Do not use the real network in JVM tests

- .github/workflows/backend-deploy.yml
Looks like both modules `gcloud` install could run in parallel and step on each other (like [here](https://github.com/joreilly/Confetti/actions/runs/5034528419/jobs/9029410914))
> Backend: run deploy sequentially

- androidApp/proguard-rules.pro
These were added in the [embedded OkHttp proguard rules](https://github.com/square/okhttp/pull/6792) in 4.11
> Remove redundant r8 rules

- .github/workflows/kmmbridgepnblish.yml
- shared/build.gradle.kts
This updates to our current standard kmmbridge configuration and should allow you to do kmmbridge publishing again. I did a test publish in my fork [here](https://github.com/russhwolf/Confetti/actions/runs/5214515183/jobs/9410876506), because Github's permission model likely won't let you run something with write permissions from my fork.
> Add missing kmmbridge configuration and update workflow to java 17 compatible version

- iosApp/ConfettiMac/Assets.xcassets/AccentColor.colorset/Contents.json
- iosApp/ConfettiMac/Assets.xcassets/AppIcon.appiconset/Contents.json
- iosApp/ConfettiMac/Assets.xcassets/Contents.json
- iosApp/ConfettiMac/ConfettiMac.entitlements
- iosApp/ConfettiMac/ConfettiMacApp.swift
- iosApp/ConfettiMac/ContentView.swift
- iosApp/ConfettiMac/Preview Content/Preview Assets.xcassets/Contents.json
- iosApp/iosApp.xcodeproj/project.pbxproj
- iosApp/iosApp.xcodeproj/xcuserdata/joreilly.xcuserdatad/xcschemes/xcschememanagement.plist
- shared/build.gradle.kts
- shared/src/macOSMain/kotlin/dev/johnoreilly/confetti/di/KoinMacOS.kt
- shared/src/macOSMain/kotlin/dev/johnoreilly/confetti/utils/MacOSDateService.kt
I've added a macos target to project's existing XCode project.....which happens to be called `iOSApp`!  Need to follow up at some point and rename that.
> macos target support + initial empty macos client

- gradle/libs.versions.toml
- wearApp/build.gradle.kts
- wearApp/src/debug/java/dev/johnoreilly/confetti/wear/ThemePreview.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/auth/FirebaseSignOutScreen.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/components/SessionSpeakerChip.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/conferences/ConferencesView.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/home/HomeScreen.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/settings/SettingsListView.kt
Update Horologist version to `0.4.10` and update usage of components.
- New version contains fixes related to a11y;
- Some components were moved from `base-ui` to `compose-material` library in `0.4.9`;
> Update Horologist version

- androidApp/src/main/java/dev/johnoreilly/confetti/conferences/ConferencesView.kt
Empty days in Conference causes `IndexOutOfBoundsException`
> Fix compose preview for ConferencesView

- androidApp/build.gradle.kts
- androidApp/proguard-rules.pro
- automotiveApp/build.gradle.kts
- automotiveApp/proguard-rules.pro
- buildSrc/build.gradle.kts
- common/car/proguard-rules.pro
- gradle/libs.versions.toml
- wearApp/build.gradle.kts
- wearApp/proguard-benchmark.pro
- wearApp/proguard-rules.pro
Now that https://github.com/firebase/firebase-android-sdk/issues/2124 is fixed, it should be fine to remove the proguard rule that keeps `com.google.android.gms.internal.*`.
Also in this PR:
- Upgrade the Firebase BoM to 32.2.0
- Exclude datastore-preferences from crashlytics and performance - the latest version of these libraries come with datastore 1.0, but this project uses an alpha version of 1.1
> Fix the issue with firebase auth in r8 fullmode

- iosApp/iosApp/Sessions/SessionListView.swift
- iosApp/iosApp/Speakers/SpeakerListView.swift
* The segmented control looks out of place because of the missing surrounding padding
* Fixes list scrolling beneath toolbar
|Before|After|
|-|-|
|<img width="496" alt="image" src="https://github.com/joreilly/Confetti/assets/17780580/1f2c929e-00cc-471f-aeda-f120f6388dde">|<img width="505" alt="image" src="https://github.com/joreilly/Confetti/assets/17780580/02588a31-627d-4e86-8a11-601ad6a4886a">|
|Before|After|
|-|-|
|<img src="https://github.com/joreilly/Confetti/assets/17780580/5f612825-fb72-41b5-964e-fcae0e8a8115" width=320/>|<img src="https://github.com/joreilly/Confetti/assets/17780580/f1207d37-e6a5-4b17-aac4-be75c609b148" width=320/>|
> refactor(ios) : adds consistent padding for the segmented control and fixes list scrolling beneath toolbar

- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/DevFestNantes.kt
🐛 Fixes session start time parsing for DevFest Nantes.
> 🐛 Fixes session start time parsing for DevFest Nantes.

- androidApp/src/main/java/dev/johnoreilly/confetti/MainActivity.kt
- androidApp/src/main/java/dev/johnoreilly/confetti/account/SignIn.kt
Google signin fails on my device with `GetCredentialResponse returned from framework`:
```
CredManProvService      dev.johnoreilly.confetti             I  GetCredentialResponse returned from framework
System.out              dev.johnoreilly.confetti             I  NoCredentialException
```
and on @emartynov one with: 
```
CredManProvService      dev.johnoreilly.confetti             I  GetCredentialResponse returned from framework
System.out              dev.johnoreilly.confetti             I  Unknown auth v2.g0@5d1613b
```
It's not 100% clear what's happening under the hood but changing from `GetGoogleIdOption` to `GetSignInWithGoogleOption` fixes the issue, at least on my device:
https://github.com/joreilly/Confetti/assets/3974977/ec3dabe0-612c-4ac8-815a-2dde6733568e
> Fix Google signin on some devices

- gradle/libs.versions.toml
- shared/build.gradle.kts
- shared/src/androidMain/kotlin/dev/johnoreilly/confetti/di/KoinAndroid.kt
- wearApp/build.gradle.kts
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/di/AppModule.kt
For both Wear and Mobile, include an Svg decoder because we don't control images.
For Wear 
- turn off crossfade (trivial performance concern)
- assume all content permanently cacheable (avoid conditional gets)
> Update Wear image loader

- gradle/libs.versions.toml
- shared/build.gradle.kts
- shared/src/androidDebug/kotlin/dev/johnoreilly/confetti/utils/ApolloDebugServer.kt
- shared/src/androidDebug/kotlin/dev/johnoreilly/confetti/utils/Environment.kt
- shared/src/androidMain/kotlin/dev/johnoreilly/confetti/utils/ApolloDebugServer.kt
- shared/src/androidRelease/kotlin/dev/johnoreilly/confetti/utils/ApolloDebugServer.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/ApolloClientCache.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/utils/ApolloDebugServer.kt
- shared/src/iosMain/kotlin/dev/johnoreilly/confetti/utils/ApolloDebugServer.kt
- shared/src/jvmMain/kotlin/dev/johnoreilly/confetti/utils/ApolloDebugServer.kt
- shared/src/macOSMain/kotlin/dev/johnoreilly/confetti/utils/ApolloDebugServer.kt
This allows the Apollo IDE plugin to connect to the app (via adb) and [visualize the normalized caches](https://www.apollographql.com/docs/kotlin/v4/testing/android-studio-plugin#normalized-cache-viewer).
> Add apollo-debug-server

- shared/src/iosMain/kotlin/dev/johnoreilly/confetti/di/KoiniOS.kt
The App crashes on iOS due to a missing dependency definition inside the `KoiniOS` file.
When we try to navigate to session details, the app crashes with the exception:
```
org.koin.core.error.NoBeanDefFoundException: No definition found for type 'com.apollographql.apollo3.cache.normalized.FetchPolicy'. Check your Modules configuration and add missing type and/or qualifier!
```
https://github.com/joreilly/Confetti/assets/45492687/5aa23f57-b41d-49e7-b4c0-3d157796bc9b
The navigation flow is fixed after adding the missing dependency definition. 
https://github.com/joreilly/Confetti/assets/45492687/52fd0757-1c0e-4759-b24d-7b6a4515693c
> Fix iOS crash - Add missing dependency definition inside KoiniOS

- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/DefaultApplication.kt
Reverts parts of https://github.com/joreilly/Confetti/pull/756. Since we're not using the router anymore, trying to push a subgraph failed. 
I'm not 100% happy with this solution. Having to go to studio to download the schema is introducing another moving part. On the other hand, using introspection doesn't return applied directives. I'll look into using `{ _service { sdl }}` from the GH action instead
> Unbreak schema reporting

- wearApp/src/main/java/dev/johnoreilly/confetti/wear/ConfettiApplication.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/networks/FirebaseUrlFactory.kt
Fix Wear Auth
Two fixes
- FirebaseUrlFactory.setRequestProperty make value nullable, which removes a header.
- Firebase Auth module needs to be considered API traffic, so it's not deferred based on networks
I can delete FirebaseUrlFactory after a horologist release
> Fix Wear authentication

- backend/service-graphql/build.gradle.kts
Just let `graphql-kotlin-spring-server` determine all dependencies, we don't need to pin `spring-web`
> Better fix for snakeyaml and spring dependencies

- .github/workflows/update-schema.yml
We used to download the schema from the Apollo Registry in CI but this has proven fragile because:
1. it requires another secret in the chain `APOLLO_KEY` 
2. it uncouples the endpoint from its schema 
3. it returns different formatted results than introspection, rendering useless diffs
This PR switches CI to use introspection instead. One of the drawback is that as part of this we lose applied schema directives (cf https://github.com/graphql/graphql-spec/issues/300) but we're not using them so far. If we were to need them, we could use a special `Query.__sdl` field for that purpose.
Also set `github_token` to have checks run in PRs
> Use GraphQL introspection instead of registry to download the schema in CI 

- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/DefaultApplication.kt
- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/firebase.kt
See https://firebase.google.com/docs/auth/admin/manage-sessions#detect_id_token_revocation
It's one additional network roundtrip but I don't see how to avoid it sadly.
> Check revocation of idTokens on the backend

- .github/workflows/update-schema.yml
See https://github.com/joreilly/Confetti/pull/1180, the GitHub action was ignoring builtin types which are needed for client side validation (see also https://github.com/graphql/graphql-wg/discussions/1391).
> Update update-graphql-schema version

- landing-page/public/.well-known/apple-app-site-association
https://developer.apple.com/documentation/xcode/supporting-associated-domains#Add-the-associated-domain-file-to-your-website
As discussed here https://kotlinlang.slack.com/archives/C051P2HUVKP/p1711750957962379?thread_ts=1711657801.535509&cid=C051P2HUVKP to try and test this
> Add the .well-known part necessary for the iOS app

- backend/service-graphql/src/main/kotlin/dev/johnoreilly/confetti/backend/graphql/model.kt
It just worked because of reflection but it was meant to be used as an argument instead.
> Hide logoUrlDark

- androidApp/src/main/java/dev/johnoreilly/confetti/MainActivity.kt
For apps like Twitter which open the app with the
Intent.FLAG_ACTIVITY_NEW_TASK flag set, and the
Intent.FLAG_ACTIVITY_CLEAR_TASK flag not set, we were experiencing very weird behavior as specified here
https://kotlinlang.slack.com/archives/C051P2HUVKP/p1712598017131459?thread_ts=1711657801.535509&cid=C051P2HUVKP
This PR imitates the way that androidx.navigation handles this scenario by clearing this activity and starting a new one which will then be in a predictably good state.
This PR applies the suggestion from here https://kotlinlang.slack.com/archives/C051P2HUVKP/p1712602985206439?thread_ts=1711657801.535509&cid=C051P2HUVKP which I have tried to test extensively to make sure that it does in fact do what we want it to do 👍
> Support deep links coming from apps which set NEW_TASK

- androidApp/src/main/res/values/strings.xml
- shared/src/commonMain/composeResources/values/strings.xml
> Remove unexpected quote escaping in string resource

- iosApp/iosApp/Sessions/SessionListView.swift
If one of the dates of a conference matches the current date, select it, use the first one otherwise.
Fixes (#1382)
> Pre-select current date if applicable

- iosApp/iosApp/Info.plist
Adds the missing flag to the Info.plist.
For some behind the scenes, check out https://youtu.be/Df1ZCmmHWzM?si=PUHYBbw0dEb3aNnA&t=839!
> Enable support for high refresh rate displays

- backend/service-import/src/jvmMain/kotlin/dev/johnoreilly/confetti/backend/import/Sessionize.kt
- backend/service-import/src/jvmTest/kotlin/test/MainTest.kt
Sessionize has an option to use local datetime or UTC instant for times. Make sure we can decode both.
> Backend: fix importing UTC dates

- .github/workflows/ios.yml
for other environments I don't think caching makes that much difference, but for iOS, saw that it takes around 20 minutes for each build, this should make it 2 times faster for next builds.
Wasn't make sure if it uses CocoaPods, so added caching option for that too just in case.
> Caching dependencies for ios build action workflow

- gradle/wrapper/gradle-wrapper.properties
Enables Gradle distribution verification by adding the expected `distributionSha256Sum` value for Gradle 8.10 within the `gradle/wrapper/gradle-wrapper.properties` file. This ensures that any local/CI processes only use the verified and [expected distribution](https://gradle.org/release-checksums/#v8.10) of Gradle, protecting against supply-chain-style attacks. [^1]
You can verify this works as expected locally by running:
```bash
./gradlew wrapper --gradle-version=8.10 --distribution-type=bin --gradle-distribution-sha256-sum=5b9c5eb3f9fc2c94abaea57d90bd78747ca117ddbbf96c859d3741181a12bf2a
```
Finally, it's my understanding that Renovate [should be able to update this value](
https://github.com/renovatebot/renovate/blob/a471762e137619c06e73a678d6b63ca984da7dba/lib/modules/manager/gradle-wr …
> Enable Gradle distribution verification

- wearApp/src/main/java/dev/johnoreilly/confetti/wear/tile/CurrentSessionsTileRenderer.kt
In reference of https://kotlinlang.slack.com/archives/C051P2HUVKP/p1730368174142119.  Here after clicking the tile service we showed an empty screen instead of the session details
From what I could see we were sending excessive curly braces around the details in the deep link. This made the config values to store the ids with these curly braces.  I'm not sure if we actually need the curly braces here for some other reason. Maybe you know better @yschimke ? If that is the case we might want to consider stripping them from the build config path instead. For now I just removed them in the deep link.
After this change it works as expected 
https://github.com/user-attachments/assets/c59c0346-df80-44dc-8249-773e4e7179d1
> Remove excessive curly brackets on session tile deeplink

- wearApp/src/main/java/dev/johnoreilly/confetti/wear/auth/WearAuthentication.kt
Refactors the Wear OS authentication implementation to support local authentication via credman.
> Improve Wear OS authentication

- gradle/libs.versions.toml
Reverts joreilly/Confetti#1484
release builds failing with
```
java.lang.NoSuchMethodError: 'void Query$QueryResponse.makeExtensionsImmutable()'
```
Presumably relating to https://github.com/protocolbuffers/protobuf/issues/19540
> Revert "Update dependency com.google.cloud:google-cloud-datastore to v2.24.3"

- gradle/libs.versions.toml
Reverts joreilly/Confetti#1497
release builds failing with
```
java.lang.NoSuchMethodError: 'void Query$QueryResponse.makeExtensionsImmutable()'
```
Presumably relating to https://github.com/protocolbuffers/protobuf/issues/19540
> Revert "Update dependency com.google.cloud:libraries-bom to v26.51.0"

- androidApp/proguard-rules.pro
- wearApp/proguard-rules.pro
Keep proto generated message classes and fields in proguard rules for both wearApp and androidApp. This prevents these classes from being obfuscated and ensures proper functionality.
> Fix: Keep proto generated message classes

- shared/src/androidMain/kotlin/dev/johnoreilly/confetti/account/SignInProcess.kt
- wearApp/src/main/java/dev/johnoreilly/confetti/wear/di/AppModule.kt
This commit updates the sign-in process to support Google Identity Services on Wear OS 5.1+.
- It introduces the `useSignInWithGoogle` flag to control whether to use Sign in With Google or the Google Identity Services API.
- On Wear OS, the `useSignInWithGoogle` flag is set to false, as the Sign in With Google UI flow is not fully supported.
> Support Google Identity Services for Wear OS

- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/fetchPolicy.kt
The interceptor introduced in #1537 fetches data in the background, which can make the UI change while the user is using the app without an action from their part. This can be confusing or annoying.
Instead, this version returns the data from the cache if it's fresh, if not, tries the network, and if that didn't work, falls back to the stale data from the cache.
Thanks @martinbonnin for the idea!
> Tweak the custom fetch policy

- androidApp/src/main/java/dev/johnoreilly/confetti/MainActivity.kt
- shared/src/androidMain/AndroidManifest.xml
- shared/src/androidMain/kotlin/dev/johnoreilly/confetti/notifications/NotificationReceiver.kt
- shared/src/androidMain/kotlin/dev/johnoreilly/confetti/notifications/SessionNotificationBuilder.kt
- shared/src/androidMain/kotlin/dev/johnoreilly/confetti/notifications/SummaryNotificationBuilder.kt
- shared/src/androidMain/kotlin/dev/johnoreilly/confetti/work/SessionNotificationSender.kt
Remove Bookmark and Content Intent.
> Add support for notification actions.

- androidApp/src/main/java/dev/johnoreilly/confetti/ConfettiApplication.kt
- shared/src/androidMain/kotlin/dev/johnoreilly/confetti/work/SessionNotificationSender.kt
- shared/src/commonMain/composeResources/values/strings.xml
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/AppSettings.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/decompose/SessionsComponent.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/decompose/SettingsComponent.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/ui/settings/SettingsUI.kt
- shared/src/commonMain/kotlin/dev/johnoreilly/confetti/work/NotificationSender.kt
Still defaults to off, but make it non experimental.
Probably still aggressively noisy for dismissed notifications, which we should remember.
> Make notifications non experimental

- gradle.properties
- gradle/libs.versions.toml
https://github.com/joreilly/Confetti/pull/1608 disabled native caching due to [CMP-7571](https://youtrack.jetbrains.com/issue/CMP-7571).
This PR bumps the relevant dependencies (Coil, Koin, and Decompose) to their latest pre-release versions which are compiled against Compose 1.8, and re-enables native caching.
> Update dependencies to re-enable native caching with CMP 1.8
